/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigNotificationsUpdateMatchersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigNotificationsUpdateMatchersRequest{}

// ConfigNotificationsUpdateMatchersRequest struct for ConfigNotificationsUpdateMatchersRequest
type ConfigNotificationsUpdateMatchersRequest struct {

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// List of properties to delete.
	Delete []PbsConfigNotificationsInlineEnum5 `json:"delete,omitempty"`

	// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty" validate:"regexp=^[a-f0-9]{64}$"`

	// Disable this matcher.
	Disable *bool `json:"disable,omitempty"`

	// Invert match of the whole filter.
	InvertMatch *bool `json:"invert-match,omitempty"`

	// List of matched severity levels.
	MatchCalendar []string `json:"match-calendar,omitempty"`

	// List of matched metadata fields.
	MatchField []string `json:"match-field,omitempty"`

	// List of matched severity levels.
	MatchSeverity []string `json:"match-severity,omitempty"`

	// The mode in which the results of matches are combined.
	Mode *PbsModeModeEnum `json:"mode,omitempty"`

	// Targets to notify.
	Target []string `json:"target,omitempty"`

}

// NewConfigNotificationsUpdateMatchersRequest instantiates a new ConfigNotificationsUpdateMatchersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigNotificationsUpdateMatchersRequest() *ConfigNotificationsUpdateMatchersRequest {
	this := ConfigNotificationsUpdateMatchersRequest{}
	var mode PbsModeModeEnum = PBSMODEMODEENUM_ALL
	this.Mode = &mode
	return &this
}

// NewConfigNotificationsUpdateMatchersRequestWithDefaults instantiates a new ConfigNotificationsUpdateMatchersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigNotificationsUpdateMatchersRequestWithDefaults() *ConfigNotificationsUpdateMatchersRequest {
	this := ConfigNotificationsUpdateMatchersRequest{}









	var mode PbsModeModeEnum = PBSMODEMODEENUM_ALL
	this.Mode = &mode


	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetComment(v string) {
	o.Comment = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDelete() []PbsConfigNotificationsInlineEnum5 {
	if o == nil || IsNil(o.Delete) {
		var ret []PbsConfigNotificationsInlineEnum5
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDeleteOk() ([]PbsConfigNotificationsInlineEnum5, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []PbsConfigNotificationsInlineEnum5 and assigns it to the Delete field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetDelete(v []PbsConfigNotificationsInlineEnum5) {
	o.Delete = v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetDisable returns the Disable field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDisable() bool {
	if o == nil || IsNil(o.Disable) {
		var ret bool
		return ret
	}
	return *o.Disable
}

// GetDisableOk returns a tuple with the Disable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetDisableOk() (*bool, bool) {
	if o == nil || IsNil(o.Disable) {
		return nil, false
	}
	return o.Disable, true
}

// HasDisable returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasDisable() bool {
	if o != nil && !IsNil(o.Disable) {
		return true
	}

	return false
}

// SetDisable gets a reference to the given bool and assigns it to the Disable field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetDisable(v bool) {
	o.Disable = &v
}


// GetInvertMatch returns the InvertMatch field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetInvertMatch() bool {
	if o == nil || IsNil(o.InvertMatch) {
		var ret bool
		return ret
	}
	return *o.InvertMatch
}

// GetInvertMatchOk returns a tuple with the InvertMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetInvertMatchOk() (*bool, bool) {
	if o == nil || IsNil(o.InvertMatch) {
		return nil, false
	}
	return o.InvertMatch, true
}

// HasInvertMatch returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasInvertMatch() bool {
	if o != nil && !IsNil(o.InvertMatch) {
		return true
	}

	return false
}

// SetInvertMatch gets a reference to the given bool and assigns it to the InvertMatch field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetInvertMatch(v bool) {
	o.InvertMatch = &v
}


// GetMatchCalendar returns the MatchCalendar field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchCalendar() []string {
	if o == nil || IsNil(o.MatchCalendar) {
		var ret []string
		return ret
	}
	return o.MatchCalendar
}

// GetMatchCalendarOk returns a tuple with the MatchCalendar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchCalendarOk() ([]string, bool) {
	if o == nil || IsNil(o.MatchCalendar) {
		return nil, false
	}
	return o.MatchCalendar, true
}

// HasMatchCalendar returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasMatchCalendar() bool {
	if o != nil && !IsNil(o.MatchCalendar) {
		return true
	}

	return false
}

// SetMatchCalendar gets a reference to the given []string and assigns it to the MatchCalendar field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetMatchCalendar(v []string) {
	o.MatchCalendar = v
}


// GetMatchField returns the MatchField field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchField() []string {
	if o == nil || IsNil(o.MatchField) {
		var ret []string
		return ret
	}
	return o.MatchField
}

// GetMatchFieldOk returns a tuple with the MatchField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchFieldOk() ([]string, bool) {
	if o == nil || IsNil(o.MatchField) {
		return nil, false
	}
	return o.MatchField, true
}

// HasMatchField returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasMatchField() bool {
	if o != nil && !IsNil(o.MatchField) {
		return true
	}

	return false
}

// SetMatchField gets a reference to the given []string and assigns it to the MatchField field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetMatchField(v []string) {
	o.MatchField = v
}


// GetMatchSeverity returns the MatchSeverity field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchSeverity() []string {
	if o == nil || IsNil(o.MatchSeverity) {
		var ret []string
		return ret
	}
	return o.MatchSeverity
}

// GetMatchSeverityOk returns a tuple with the MatchSeverity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMatchSeverityOk() ([]string, bool) {
	if o == nil || IsNil(o.MatchSeverity) {
		return nil, false
	}
	return o.MatchSeverity, true
}

// HasMatchSeverity returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasMatchSeverity() bool {
	if o != nil && !IsNil(o.MatchSeverity) {
		return true
	}

	return false
}

// SetMatchSeverity gets a reference to the given []string and assigns it to the MatchSeverity field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetMatchSeverity(v []string) {
	o.MatchSeverity = v
}


// GetMode returns the Mode field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetMode() PbsModeModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret PbsModeModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetModeOk() (*PbsModeModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given PbsModeModeEnum and assigns it to the Mode field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetMode(v PbsModeModeEnum) {
	o.Mode = &v
}


// GetTarget returns the Target field value if set, zero value otherwise.
func (o *ConfigNotificationsUpdateMatchersRequest) GetTarget() []string {
	if o == nil || IsNil(o.Target) {
		var ret []string
		return ret
	}
	return o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) GetTargetOk() ([]string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *ConfigNotificationsUpdateMatchersRequest) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given []string and assigns it to the Target field.
func (o *ConfigNotificationsUpdateMatchersRequest) SetTarget(v []string) {
	o.Target = v
}


func (o ConfigNotificationsUpdateMatchersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigNotificationsUpdateMatchersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.Disable) {
		toSerialize["disable"] = o.Disable
	}
	
	if !IsNil(o.InvertMatch) {
		toSerialize["invert-match"] = o.InvertMatch
	}
	
	if !IsNil(o.MatchCalendar) {
		toSerialize["match-calendar"] = o.MatchCalendar
	}
	
	if !IsNil(o.MatchField) {
		toSerialize["match-field"] = o.MatchField
	}
	
	if !IsNil(o.MatchSeverity) {
		toSerialize["match-severity"] = o.MatchSeverity
	}
	
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	
	return toSerialize, nil
}

type NullableConfigNotificationsUpdateMatchersRequest struct {
	value *ConfigNotificationsUpdateMatchersRequest
	isSet bool
}

func (v NullableConfigNotificationsUpdateMatchersRequest) Get() *ConfigNotificationsUpdateMatchersRequest {
	return v.value
}

func (v *NullableConfigNotificationsUpdateMatchersRequest) Set(val *ConfigNotificationsUpdateMatchersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigNotificationsUpdateMatchersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigNotificationsUpdateMatchersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigNotificationsUpdateMatchersRequest(val *ConfigNotificationsUpdateMatchersRequest) *NullableConfigNotificationsUpdateMatchersRequest {
	return &NullableConfigNotificationsUpdateMatchersRequest{value: val, isSet: true}
}

func (v NullableConfigNotificationsUpdateMatchersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigNotificationsUpdateMatchersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


