/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsAccessAclUgidTypeEnum the model 'PbsAccessAclUgidTypeEnum'
type PbsAccessAclUgidTypeEnum string

// List of PbsAccessAclUgidTypeEnum
const (
	PBSACCESSACLUGIDTYPEENUM_USER PbsAccessAclUgidTypeEnum = "user"
	PBSACCESSACLUGIDTYPEENUM_GROUP PbsAccessAclUgidTypeEnum = "group"
)

// All allowed values of PbsAccessAclUgidTypeEnum enum
var AllowedPbsAccessAclUgidTypeEnumEnumValues = []PbsAccessAclUgidTypeEnum{
	"user",
	"group",
}

func (v *PbsAccessAclUgidTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsAccessAclUgidTypeEnum(value)
	for _, existing := range AllowedPbsAccessAclUgidTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsAccessAclUgidTypeEnum", value)
}

// NewPbsAccessAclUgidTypeEnumFromValue returns a pointer to a valid PbsAccessAclUgidTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsAccessAclUgidTypeEnumFromValue(v string) (*PbsAccessAclUgidTypeEnum, error) {
	ev := PbsAccessAclUgidTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsAccessAclUgidTypeEnum: valid values are %v", v, AllowedPbsAccessAclUgidTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsAccessAclUgidTypeEnum) IsValid() bool {
	for _, existing := range AllowedPbsAccessAclUgidTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsAccessAclUgidTypeEnum value
func (v PbsAccessAclUgidTypeEnum) Ptr() *PbsAccessAclUgidTypeEnum {
	return &v
}

type NullablePbsAccessAclUgidTypeEnum struct {
	value *PbsAccessAclUgidTypeEnum
	isSet bool
}

func (v NullablePbsAccessAclUgidTypeEnum) Get() *PbsAccessAclUgidTypeEnum {
	return v.value
}

func (v *NullablePbsAccessAclUgidTypeEnum) Set(val *PbsAccessAclUgidTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsAccessAclUgidTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsAccessAclUgidTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsAccessAclUgidTypeEnum(val *PbsAccessAclUgidTypeEnum) *NullablePbsAccessAclUgidTypeEnum {
	return &NullablePbsAccessAclUgidTypeEnum{value: val, isSet: true}
}

func (v NullablePbsAccessAclUgidTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsAccessAclUgidTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

