/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NodesDisksGetListResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesDisksGetListResponseDataInner{}

// NodesDisksGetListResponseDataInner struct for NodesDisksGetListResponseDataInner
type NodesDisksGetListResponseDataInner struct {

	// Linux device path (/dev/xxx)
	Devpath *string `json:"devpath,omitempty"`

	// This is just a rough estimate for a \"type\" of disk.
	DiskType PbsNodesDisksDiskTypeEnum `json:"disk-type"`

	// Set if disk contains a GPT partition table
	Gpt bool `json:"gpt"`

	// Model
	Model *string `json:"model,omitempty"`

	// Disk name (`/sys/block/<name>`)
	Name string `json:"name"`

	// Partitions on the device
	Partitions []NodesDisksGetListResponseDataInnerPartitionsInner `json:"partitions,omitempty"`

	// RPM
	Rpm *int64 `json:"rpm,omitempty"`

	// Serisal number
	Serial *string `json:"serial,omitempty"`

	// Disk size
	Size int64 `json:"size"`

	// SMART status
	Status PbsStatusEnum `json:"status"`

	// What a block device (disk) is used for.
	Used PbsUsageTypeEnum `json:"used"`

	// Vendor
	Vendor *string `json:"vendor,omitempty"`

	// Disk wearout
	Wearout *float32 `json:"wearout,omitempty"`

	// WWN
	Wwn *string `json:"wwn,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _NodesDisksGetListResponseDataInner NodesDisksGetListResponseDataInner

// NewNodesDisksGetListResponseDataInner instantiates a new NodesDisksGetListResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesDisksGetListResponseDataInner(diskType PbsNodesDisksDiskTypeEnum, gpt bool, name string, size int64, status PbsStatusEnum, used PbsUsageTypeEnum) *NodesDisksGetListResponseDataInner {
	this := NodesDisksGetListResponseDataInner{}
	this.DiskType = diskType
	this.Gpt = gpt
	this.Name = name
	this.Size = size
	this.Status = status
	this.Used = used
	return &this
}

// NewNodesDisksGetListResponseDataInnerWithDefaults instantiates a new NodesDisksGetListResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesDisksGetListResponseDataInnerWithDefaults() *NodesDisksGetListResponseDataInner {
	this := NodesDisksGetListResponseDataInner{}















	return &this
}


// GetDevpath returns the Devpath field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetDevpath() string {
	if o == nil || IsNil(o.Devpath) {
		var ret string
		return ret
	}
	return *o.Devpath
}

// GetDevpathOk returns a tuple with the Devpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetDevpathOk() (*string, bool) {
	if o == nil || IsNil(o.Devpath) {
		return nil, false
	}
	return o.Devpath, true
}

// HasDevpath returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasDevpath() bool {
	if o != nil && !IsNil(o.Devpath) {
		return true
	}

	return false
}

// SetDevpath gets a reference to the given string and assigns it to the Devpath field.
func (o *NodesDisksGetListResponseDataInner) SetDevpath(v string) {
	o.Devpath = &v
}


// GetDiskType returns the DiskType field value
func (o *NodesDisksGetListResponseDataInner) GetDiskType() PbsNodesDisksDiskTypeEnum {
	if o == nil {
		var ret PbsNodesDisksDiskTypeEnum
		return ret
	}

	return o.DiskType
}

// GetDiskTypeOk returns a tuple with the DiskType field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetDiskTypeOk() (*PbsNodesDisksDiskTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskType, true
}

// SetDiskType sets field value
func (o *NodesDisksGetListResponseDataInner) SetDiskType(v PbsNodesDisksDiskTypeEnum) {
	o.DiskType = v
}


// GetGpt returns the Gpt field value
func (o *NodesDisksGetListResponseDataInner) GetGpt() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Gpt
}

// GetGptOk returns a tuple with the Gpt field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetGptOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gpt, true
}

// SetGpt sets field value
func (o *NodesDisksGetListResponseDataInner) SetGpt(v bool) {
	o.Gpt = v
}


// GetModel returns the Model field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *NodesDisksGetListResponseDataInner) SetModel(v string) {
	o.Model = &v
}


// GetName returns the Name field value
func (o *NodesDisksGetListResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodesDisksGetListResponseDataInner) SetName(v string) {
	o.Name = v
}


// GetPartitions returns the Partitions field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetPartitions() []NodesDisksGetListResponseDataInnerPartitionsInner {
	if o == nil || IsNil(o.Partitions) {
		var ret []NodesDisksGetListResponseDataInnerPartitionsInner
		return ret
	}
	return o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetPartitionsOk() ([]NodesDisksGetListResponseDataInnerPartitionsInner, bool) {
	if o == nil || IsNil(o.Partitions) {
		return nil, false
	}
	return o.Partitions, true
}

// HasPartitions returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasPartitions() bool {
	if o != nil && !IsNil(o.Partitions) {
		return true
	}

	return false
}

// SetPartitions gets a reference to the given []NodesDisksGetListResponseDataInnerPartitionsInner and assigns it to the Partitions field.
func (o *NodesDisksGetListResponseDataInner) SetPartitions(v []NodesDisksGetListResponseDataInnerPartitionsInner) {
	o.Partitions = v
}


// GetRpm returns the Rpm field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetRpm() int64 {
	if o == nil || IsNil(o.Rpm) {
		var ret int64
		return ret
	}
	return *o.Rpm
}

// GetRpmOk returns a tuple with the Rpm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetRpmOk() (*int64, bool) {
	if o == nil || IsNil(o.Rpm) {
		return nil, false
	}
	return o.Rpm, true
}

// HasRpm returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasRpm() bool {
	if o != nil && !IsNil(o.Rpm) {
		return true
	}

	return false
}

// SetRpm gets a reference to the given int64 and assigns it to the Rpm field.
func (o *NodesDisksGetListResponseDataInner) SetRpm(v int64) {
	o.Rpm = &v
}


// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *NodesDisksGetListResponseDataInner) SetSerial(v string) {
	o.Serial = &v
}


// GetSize returns the Size field value
func (o *NodesDisksGetListResponseDataInner) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *NodesDisksGetListResponseDataInner) SetSize(v int64) {
	o.Size = v
}


// GetStatus returns the Status field value
func (o *NodesDisksGetListResponseDataInner) GetStatus() PbsStatusEnum {
	if o == nil {
		var ret PbsStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetStatusOk() (*PbsStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NodesDisksGetListResponseDataInner) SetStatus(v PbsStatusEnum) {
	o.Status = v
}


// GetUsed returns the Used field value
func (o *NodesDisksGetListResponseDataInner) GetUsed() PbsUsageTypeEnum {
	if o == nil {
		var ret PbsUsageTypeEnum
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetUsedOk() (*PbsUsageTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *NodesDisksGetListResponseDataInner) SetUsed(v PbsUsageTypeEnum) {
	o.Used = v
}


// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *NodesDisksGetListResponseDataInner) SetVendor(v string) {
	o.Vendor = &v
}


// GetWearout returns the Wearout field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetWearout() float32 {
	if o == nil || IsNil(o.Wearout) {
		var ret float32
		return ret
	}
	return *o.Wearout
}

// GetWearoutOk returns a tuple with the Wearout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetWearoutOk() (*float32, bool) {
	if o == nil || IsNil(o.Wearout) {
		return nil, false
	}
	return o.Wearout, true
}

// HasWearout returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasWearout() bool {
	if o != nil && !IsNil(o.Wearout) {
		return true
	}

	return false
}

// SetWearout gets a reference to the given float32 and assigns it to the Wearout field.
func (o *NodesDisksGetListResponseDataInner) SetWearout(v float32) {
	o.Wearout = &v
}


// GetWwn returns the Wwn field value if set, zero value otherwise.
func (o *NodesDisksGetListResponseDataInner) GetWwn() string {
	if o == nil || IsNil(o.Wwn) {
		var ret string
		return ret
	}
	return *o.Wwn
}

// GetWwnOk returns a tuple with the Wwn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesDisksGetListResponseDataInner) GetWwnOk() (*string, bool) {
	if o == nil || IsNil(o.Wwn) {
		return nil, false
	}
	return o.Wwn, true
}

// HasWwn returns a boolean if a field has been set.
func (o *NodesDisksGetListResponseDataInner) HasWwn() bool {
	if o != nil && !IsNil(o.Wwn) {
		return true
	}

	return false
}

// SetWwn gets a reference to the given string and assigns it to the Wwn field.
func (o *NodesDisksGetListResponseDataInner) SetWwn(v string) {
	o.Wwn = &v
}


func (o NodesDisksGetListResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesDisksGetListResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Devpath) {
		toSerialize["devpath"] = o.Devpath
	}
	
	toSerialize["disk-type"] = o.DiskType
	
	toSerialize["gpt"] = o.Gpt
	
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	
	toSerialize["name"] = o.Name
	
	if !IsNil(o.Partitions) {
		toSerialize["partitions"] = o.Partitions
	}
	
	if !IsNil(o.Rpm) {
		toSerialize["rpm"] = o.Rpm
	}
	
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	
	toSerialize["size"] = o.Size
	
	toSerialize["status"] = o.Status
	
	toSerialize["used"] = o.Used
	
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	
	if !IsNil(o.Wearout) {
		toSerialize["wearout"] = o.Wearout
	}
	
	if !IsNil(o.Wwn) {
		toSerialize["wwn"] = o.Wwn
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodesDisksGetListResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disk-type",
		"gpt",
		"name",
		"size",
		"status",
		"used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodesDisksGetListResponseDataInner := _NodesDisksGetListResponseDataInner{}

	err = json.Unmarshal(data, &varNodesDisksGetListResponseDataInner)

	if err != nil {
		return err
	}

	*o = NodesDisksGetListResponseDataInner(varNodesDisksGetListResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "devpath")
		delete(additionalProperties, "disk-type")
		delete(additionalProperties, "gpt")
		delete(additionalProperties, "model")
		delete(additionalProperties, "name")
		delete(additionalProperties, "partitions")
		delete(additionalProperties, "rpm")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "size")
		delete(additionalProperties, "status")
		delete(additionalProperties, "used")
		delete(additionalProperties, "vendor")
		delete(additionalProperties, "wearout")
		delete(additionalProperties, "wwn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodesDisksGetListResponseDataInner struct {
	value *NodesDisksGetListResponseDataInner
	isSet bool
}

func (v NullableNodesDisksGetListResponseDataInner) Get() *NodesDisksGetListResponseDataInner {
	return v.value
}

func (v *NullableNodesDisksGetListResponseDataInner) Set(val *NodesDisksGetListResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesDisksGetListResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesDisksGetListResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesDisksGetListResponseDataInner(val *NodesDisksGetListResponseDataInner) *NullableNodesDisksGetListResponseDataInner {
	return &NullableNodesDisksGetListResponseDataInner{value: val, isSet: true}
}

func (v NullableNodesDisksGetListResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesDisksGetListResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


