/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsConfigAcmeInlineEnum the model 'PbsConfigAcmeInlineEnum'
type PbsConfigAcmeInlineEnum string

// List of PbsConfigAcmeInlineEnum
const (
	PBSCONFIGACMEINLINEENUM_DISABLE PbsConfigAcmeInlineEnum = "disable"
	PBSCONFIGACMEINLINEENUM_VALIDATION_DELAY PbsConfigAcmeInlineEnum = "validation-delay"
)

// All allowed values of PbsConfigAcmeInlineEnum enum
var AllowedPbsConfigAcmeInlineEnumEnumValues = []PbsConfigAcmeInlineEnum{
	"disable",
	"validation-delay",
}

func (v *PbsConfigAcmeInlineEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsConfigAcmeInlineEnum(value)
	for _, existing := range AllowedPbsConfigAcmeInlineEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsConfigAcmeInlineEnum", value)
}

// NewPbsConfigAcmeInlineEnumFromValue returns a pointer to a valid PbsConfigAcmeInlineEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsConfigAcmeInlineEnumFromValue(v string) (*PbsConfigAcmeInlineEnum, error) {
	ev := PbsConfigAcmeInlineEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsConfigAcmeInlineEnum: valid values are %v", v, AllowedPbsConfigAcmeInlineEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsConfigAcmeInlineEnum) IsValid() bool {
	for _, existing := range AllowedPbsConfigAcmeInlineEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsConfigAcmeInlineEnum value
func (v PbsConfigAcmeInlineEnum) Ptr() *PbsConfigAcmeInlineEnum {
	return &v
}

type NullablePbsConfigAcmeInlineEnum struct {
	value *PbsConfigAcmeInlineEnum
	isSet bool
}

func (v NullablePbsConfigAcmeInlineEnum) Get() *PbsConfigAcmeInlineEnum {
	return v.value
}

func (v *NullablePbsConfigAcmeInlineEnum) Set(val *PbsConfigAcmeInlineEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsConfigAcmeInlineEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsConfigAcmeInlineEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsConfigAcmeInlineEnum(val *PbsConfigAcmeInlineEnum) *NullablePbsConfigAcmeInlineEnum {
	return &NullablePbsConfigAcmeInlineEnum{value: val, isSet: true}
}

func (v NullablePbsConfigAcmeInlineEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsConfigAcmeInlineEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

