/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PbsExportSlotsField - struct for PbsExportSlotsField
type PbsExportSlotsField struct {
	PbsExportSlotsConfig *PbsExportSlotsConfig
	String *string
}

// PbsExportSlotsConfigAsPbsExportSlotsField is a convenience function that returns PbsExportSlotsConfig wrapped in PbsExportSlotsField
func PbsExportSlotsConfigAsPbsExportSlotsField(v *PbsExportSlotsConfig) PbsExportSlotsField {
	return PbsExportSlotsField{
		PbsExportSlotsConfig: v,
	}
}

// stringAsPbsExportSlotsField is a convenience function that returns string wrapped in PbsExportSlotsField
func StringAsPbsExportSlotsField(v *string) PbsExportSlotsField {
	return PbsExportSlotsField{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PbsExportSlotsField) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PbsExportSlotsConfig
	err = newStrictDecoder(data).Decode(&dst.PbsExportSlotsConfig)
	if err == nil {
		jsonPbsExportSlotsConfig, _ := json.Marshal(dst.PbsExportSlotsConfig)
		if string(jsonPbsExportSlotsConfig) == "{}" { // empty struct
			dst.PbsExportSlotsConfig = nil
		} else {
			if err = validator.Validate(dst.PbsExportSlotsConfig); err != nil {
				dst.PbsExportSlotsConfig = nil
			} else {
				match++
			}
		}
	} else {
		dst.PbsExportSlotsConfig = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PbsExportSlotsConfig = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PbsExportSlotsField)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PbsExportSlotsField)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PbsExportSlotsField) MarshalJSON() ([]byte, error) {
	if src.PbsExportSlotsConfig != nil {
		return json.Marshal(&src.PbsExportSlotsConfig)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PbsExportSlotsField) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PbsExportSlotsConfig != nil {
		return obj.PbsExportSlotsConfig
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PbsExportSlotsField) GetActualInstanceValue() (interface{}) {
	if obj.PbsExportSlotsConfig != nil {
		return *obj.PbsExportSlotsConfig
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePbsExportSlotsField struct {
	value *PbsExportSlotsField
	isSet bool
}

func (v NullablePbsExportSlotsField) Get() *PbsExportSlotsField {
	return v.value
}

func (v *NullablePbsExportSlotsField) Set(val *PbsExportSlotsField) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsExportSlotsField) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsExportSlotsField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsExportSlotsField(val *PbsExportSlotsField) *NullablePbsExportSlotsField {
	return &NullablePbsExportSlotsField{value: val, isSet: true}
}

func (v NullablePbsExportSlotsField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsExportSlotsField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


