/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PbsDevicesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PbsDevicesConfig{}

// PbsDevicesConfig struct for PbsDevicesConfig
type PbsDevicesConfig struct {

	Description interface{} `json:"description"`

	// Block device name (/sys/block/<name>).
	Items string `json:"items" validate:"regexp=^(?:(?:h|s|x?v)d[a-z]+)|(?:nvme\\\\d+n\\\\d+)$"`

	Type interface{} `json:"type"`

}

type _PbsDevicesConfig PbsDevicesConfig

// NewPbsDevicesConfig instantiates a new PbsDevicesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPbsDevicesConfig(description interface{}, items string, type_ interface{}) *PbsDevicesConfig {
	this := PbsDevicesConfig{}
	this.Description = description
	this.Items = items
	this.Type = type_
	return &this
}

// NewPbsDevicesConfigWithDefaults instantiates a new PbsDevicesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPbsDevicesConfigWithDefaults() *PbsDevicesConfig {
	this := PbsDevicesConfig{}




	return &this
}


// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PbsDevicesConfig) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PbsDevicesConfig) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PbsDevicesConfig) SetDescription(v interface{}) {
	o.Description = v
}


// GetItems returns the Items field value
func (o *PbsDevicesConfig) GetItems() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PbsDevicesConfig) GetItemsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *PbsDevicesConfig) SetItems(v string) {
	o.Items = v
}


// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PbsDevicesConfig) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PbsDevicesConfig) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PbsDevicesConfig) SetType(v interface{}) {
	o.Type = v
}


func (o PbsDevicesConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PbsDevicesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	
	toSerialize["items"] = o.Items
	
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	
	return toSerialize, nil
}

func (o *PbsDevicesConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"items",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPbsDevicesConfig := _PbsDevicesConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPbsDevicesConfig)

	if err != nil {
		return err
	}

	*o = PbsDevicesConfig(varPbsDevicesConfig)

	return err
}

type NullablePbsDevicesConfig struct {
	value *PbsDevicesConfig
	isSet bool
}

func (v NullablePbsDevicesConfig) Get() *PbsDevicesConfig {
	return v.value
}

func (v *NullablePbsDevicesConfig) Set(val *PbsDevicesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsDevicesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsDevicesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsDevicesConfig(val *PbsDevicesConfig) *NullablePbsDevicesConfig {
	return &NullablePbsDevicesConfig{value: val, isSet: true}
}

func (v NullablePbsDevicesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsDevicesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


