/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigS3GetS3Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigS3GetS3Response{}

// ConfigS3GetS3Response struct for ConfigS3GetS3Response
type ConfigS3GetS3Response struct {

	Data []ConfigS3GetS3ResponseDataInner `json:"data"`

	// Optional total count, present for paginated list responses.
	Total *int32 `json:"total,omitempty"`

	// Optional change summary returned by some PUT operations (one entry per modified field).
	Changes map[string]interface{} `json:"changes,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ConfigS3GetS3Response ConfigS3GetS3Response

// NewConfigS3GetS3Response instantiates a new ConfigS3GetS3Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigS3GetS3Response(data []ConfigS3GetS3ResponseDataInner) *ConfigS3GetS3Response {
	this := ConfigS3GetS3Response{}
	this.Data = data
	return &this
}

// NewConfigS3GetS3ResponseWithDefaults instantiates a new ConfigS3GetS3Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigS3GetS3ResponseWithDefaults() *ConfigS3GetS3Response {
	this := ConfigS3GetS3Response{}




	return &this
}


// GetData returns the Data field value
func (o *ConfigS3GetS3Response) GetData() []ConfigS3GetS3ResponseDataInner {
	if o == nil {
		var ret []ConfigS3GetS3ResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfigS3GetS3Response) GetDataOk() ([]ConfigS3GetS3ResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ConfigS3GetS3Response) SetData(v []ConfigS3GetS3ResponseDataInner) {
	o.Data = v
}


// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ConfigS3GetS3Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigS3GetS3Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ConfigS3GetS3Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ConfigS3GetS3Response) SetTotal(v int32) {
	o.Total = &v
}


// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *ConfigS3GetS3Response) GetChanges() map[string]interface{} {
	if o == nil || IsNil(o.Changes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigS3GetS3Response) GetChangesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Changes) {
		return map[string]interface{}{}, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *ConfigS3GetS3Response) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given map[string]interface{} and assigns it to the Changes field.
func (o *ConfigS3GetS3Response) SetChanges(v map[string]interface{}) {
	o.Changes = v
}


func (o ConfigS3GetS3Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigS3GetS3Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["data"] = o.Data
	
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigS3GetS3Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigS3GetS3Response := _ConfigS3GetS3Response{}

	err = json.Unmarshal(data, &varConfigS3GetS3Response)

	if err != nil {
		return err
	}

	*o = ConfigS3GetS3Response(varConfigS3GetS3Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "total")
		delete(additionalProperties, "changes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigS3GetS3Response struct {
	value *ConfigS3GetS3Response
	isSet bool
}

func (v NullableConfigS3GetS3Response) Get() *ConfigS3GetS3Response {
	return v.value
}

func (v *NullableConfigS3GetS3Response) Set(val *ConfigS3GetS3Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigS3GetS3Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigS3GetS3Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigS3GetS3Response(val *ConfigS3GetS3Response) *NullableConfigS3GetS3Response {
	return &NullableConfigS3GetS3Response{value: val, isSet: true}
}

func (v NullableConfigS3GetS3Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigS3GetS3Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


