/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigTrafficControlCreateTrafficControlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigTrafficControlCreateTrafficControlRequest{}

// ConfigTrafficControlCreateTrafficControlRequest struct for ConfigTrafficControlCreateTrafficControlRequest
type ConfigTrafficControlCreateTrafficControlRequest struct {

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstIn *string `json:"burst-in,omitempty"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstOut *string `json:"burst-out,omitempty"`

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// Rule ID.
	Name string `json:"name" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// Rule applies to Source IPs within this networks
	Network []string `json:"network"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateIn *string `json:"rate-in,omitempty"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateOut *string `json:"rate-out,omitempty"`

	// Enable the rule at specific times
	Timeframe []string `json:"timeframe,omitempty"`

	// Rule applies to authenticated API requests of any of these users (overrides IP-only rules)
	Users []string `json:"users,omitempty"`

}

type _ConfigTrafficControlCreateTrafficControlRequest ConfigTrafficControlCreateTrafficControlRequest

// NewConfigTrafficControlCreateTrafficControlRequest instantiates a new ConfigTrafficControlCreateTrafficControlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigTrafficControlCreateTrafficControlRequest(name string, network []string) *ConfigTrafficControlCreateTrafficControlRequest {
	this := ConfigTrafficControlCreateTrafficControlRequest{}
	this.Name = name
	this.Network = network
	return &this
}

// NewConfigTrafficControlCreateTrafficControlRequestWithDefaults instantiates a new ConfigTrafficControlCreateTrafficControlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigTrafficControlCreateTrafficControlRequestWithDefaults() *ConfigTrafficControlCreateTrafficControlRequest {
	this := ConfigTrafficControlCreateTrafficControlRequest{}










	return &this
}


// GetBurstIn returns the BurstIn field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetBurstIn() string {
	if o == nil || IsNil(o.BurstIn) {
		var ret string
		return ret
	}
	return *o.BurstIn
}

// GetBurstInOk returns a tuple with the BurstIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetBurstInOk() (*string, bool) {
	if o == nil || IsNil(o.BurstIn) {
		return nil, false
	}
	return o.BurstIn, true
}

// HasBurstIn returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasBurstIn() bool {
	if o != nil && !IsNil(o.BurstIn) {
		return true
	}

	return false
}

// SetBurstIn gets a reference to the given string and assigns it to the BurstIn field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetBurstIn(v string) {
	o.BurstIn = &v
}


// GetBurstOut returns the BurstOut field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetBurstOut() string {
	if o == nil || IsNil(o.BurstOut) {
		var ret string
		return ret
	}
	return *o.BurstOut
}

// GetBurstOutOk returns a tuple with the BurstOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetBurstOutOk() (*string, bool) {
	if o == nil || IsNil(o.BurstOut) {
		return nil, false
	}
	return o.BurstOut, true
}

// HasBurstOut returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasBurstOut() bool {
	if o != nil && !IsNil(o.BurstOut) {
		return true
	}

	return false
}

// SetBurstOut gets a reference to the given string and assigns it to the BurstOut field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetBurstOut(v string) {
	o.BurstOut = &v
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetComment(v string) {
	o.Comment = &v
}


// GetName returns the Name field value
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetName(v string) {
	o.Name = v
}


// GetNetwork returns the Network field value
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetNetwork() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetNetworkOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Network, true
}

// SetNetwork sets field value
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetNetwork(v []string) {
	o.Network = v
}


// GetRateIn returns the RateIn field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetRateIn() string {
	if o == nil || IsNil(o.RateIn) {
		var ret string
		return ret
	}
	return *o.RateIn
}

// GetRateInOk returns a tuple with the RateIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetRateInOk() (*string, bool) {
	if o == nil || IsNil(o.RateIn) {
		return nil, false
	}
	return o.RateIn, true
}

// HasRateIn returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasRateIn() bool {
	if o != nil && !IsNil(o.RateIn) {
		return true
	}

	return false
}

// SetRateIn gets a reference to the given string and assigns it to the RateIn field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetRateIn(v string) {
	o.RateIn = &v
}


// GetRateOut returns the RateOut field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetRateOut() string {
	if o == nil || IsNil(o.RateOut) {
		var ret string
		return ret
	}
	return *o.RateOut
}

// GetRateOutOk returns a tuple with the RateOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetRateOutOk() (*string, bool) {
	if o == nil || IsNil(o.RateOut) {
		return nil, false
	}
	return o.RateOut, true
}

// HasRateOut returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasRateOut() bool {
	if o != nil && !IsNil(o.RateOut) {
		return true
	}

	return false
}

// SetRateOut gets a reference to the given string and assigns it to the RateOut field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetRateOut(v string) {
	o.RateOut = &v
}


// GetTimeframe returns the Timeframe field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetTimeframe() []string {
	if o == nil || IsNil(o.Timeframe) {
		var ret []string
		return ret
	}
	return o.Timeframe
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetTimeframeOk() ([]string, bool) {
	if o == nil || IsNil(o.Timeframe) {
		return nil, false
	}
	return o.Timeframe, true
}

// HasTimeframe returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasTimeframe() bool {
	if o != nil && !IsNil(o.Timeframe) {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given []string and assigns it to the Timeframe field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetTimeframe(v []string) {
	o.Timeframe = v
}


// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ConfigTrafficControlCreateTrafficControlRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *ConfigTrafficControlCreateTrafficControlRequest) SetUsers(v []string) {
	o.Users = v
}


func (o ConfigTrafficControlCreateTrafficControlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigTrafficControlCreateTrafficControlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.BurstIn) {
		toSerialize["burst-in"] = o.BurstIn
	}
	
	if !IsNil(o.BurstOut) {
		toSerialize["burst-out"] = o.BurstOut
	}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	toSerialize["name"] = o.Name
	
	toSerialize["network"] = o.Network
	
	if !IsNil(o.RateIn) {
		toSerialize["rate-in"] = o.RateIn
	}
	
	if !IsNil(o.RateOut) {
		toSerialize["rate-out"] = o.RateOut
	}
	
	if !IsNil(o.Timeframe) {
		toSerialize["timeframe"] = o.Timeframe
	}
	
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	
	return toSerialize, nil
}

func (o *ConfigTrafficControlCreateTrafficControlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigTrafficControlCreateTrafficControlRequest := _ConfigTrafficControlCreateTrafficControlRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigTrafficControlCreateTrafficControlRequest)

	if err != nil {
		return err
	}

	*o = ConfigTrafficControlCreateTrafficControlRequest(varConfigTrafficControlCreateTrafficControlRequest)

	return err
}

type NullableConfigTrafficControlCreateTrafficControlRequest struct {
	value *ConfigTrafficControlCreateTrafficControlRequest
	isSet bool
}

func (v NullableConfigTrafficControlCreateTrafficControlRequest) Get() *ConfigTrafficControlCreateTrafficControlRequest {
	return v.value
}

func (v *NullableConfigTrafficControlCreateTrafficControlRequest) Set(val *ConfigTrafficControlCreateTrafficControlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigTrafficControlCreateTrafficControlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigTrafficControlCreateTrafficControlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigTrafficControlCreateTrafficControlRequest(val *ConfigTrafficControlCreateTrafficControlRequest) *NullableConfigTrafficControlCreateTrafficControlRequest {
	return &NullableConfigTrafficControlCreateTrafficControlRequest{value: val, isSet: true}
}

func (v NullableConfigTrafficControlCreateTrafficControlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigTrafficControlCreateTrafficControlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


