/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsNodesDisksRaidlevelEnum the model 'PbsNodesDisksRaidlevelEnum'
type PbsNodesDisksRaidlevelEnum string

// List of PbsNodesDisksRaidlevelEnum
const (
	PBSNODESDISKSRAIDLEVELENUM_SINGLE PbsNodesDisksRaidlevelEnum = "single"
	PBSNODESDISKSRAIDLEVELENUM_MIRROR PbsNodesDisksRaidlevelEnum = "mirror"
	PBSNODESDISKSRAIDLEVELENUM_RAID10 PbsNodesDisksRaidlevelEnum = "raid10"
	PBSNODESDISKSRAIDLEVELENUM_RAIDZ PbsNodesDisksRaidlevelEnum = "raidz"
	PBSNODESDISKSRAIDLEVELENUM_RAIDZ2 PbsNodesDisksRaidlevelEnum = "raidz2"
	PBSNODESDISKSRAIDLEVELENUM_RAIDZ3 PbsNodesDisksRaidlevelEnum = "raidz3"
)

// All allowed values of PbsNodesDisksRaidlevelEnum enum
var AllowedPbsNodesDisksRaidlevelEnumEnumValues = []PbsNodesDisksRaidlevelEnum{
	"single",
	"mirror",
	"raid10",
	"raidz",
	"raidz2",
	"raidz3",
}

func (v *PbsNodesDisksRaidlevelEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsNodesDisksRaidlevelEnum(value)
	for _, existing := range AllowedPbsNodesDisksRaidlevelEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsNodesDisksRaidlevelEnum", value)
}

// NewPbsNodesDisksRaidlevelEnumFromValue returns a pointer to a valid PbsNodesDisksRaidlevelEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsNodesDisksRaidlevelEnumFromValue(v string) (*PbsNodesDisksRaidlevelEnum, error) {
	ev := PbsNodesDisksRaidlevelEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsNodesDisksRaidlevelEnum: valid values are %v", v, AllowedPbsNodesDisksRaidlevelEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsNodesDisksRaidlevelEnum) IsValid() bool {
	for _, existing := range AllowedPbsNodesDisksRaidlevelEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsNodesDisksRaidlevelEnum value
func (v PbsNodesDisksRaidlevelEnum) Ptr() *PbsNodesDisksRaidlevelEnum {
	return &v
}

type NullablePbsNodesDisksRaidlevelEnum struct {
	value *PbsNodesDisksRaidlevelEnum
	isSet bool
}

func (v NullablePbsNodesDisksRaidlevelEnum) Get() *PbsNodesDisksRaidlevelEnum {
	return v.value
}

func (v *NullablePbsNodesDisksRaidlevelEnum) Set(val *PbsNodesDisksRaidlevelEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsNodesDisksRaidlevelEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsNodesDisksRaidlevelEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsNodesDisksRaidlevelEnum(val *PbsNodesDisksRaidlevelEnum) *NullablePbsNodesDisksRaidlevelEnum {
	return &NullablePbsNodesDisksRaidlevelEnum{value: val, isSet: true}
}

func (v NullablePbsNodesDisksRaidlevelEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsNodesDisksRaidlevelEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

