/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigAccessGetPamResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigAccessGetPamResponseData{}

// ConfigAccessGetPamResponseData struct for ConfigAccessGetPamResponseData
type ConfigAccessGetPamResponseData struct {

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// True if you want this to be the default realm selected on login.
	Default *bool `json:"default,omitempty"`

	// Realm name.
	Realm string `json:"realm" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// type of the realm
	Type PbsTypeEnum `json:"type"`

	AdditionalProperties map[string]interface{}
}

type _ConfigAccessGetPamResponseData ConfigAccessGetPamResponseData

// NewConfigAccessGetPamResponseData instantiates a new ConfigAccessGetPamResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigAccessGetPamResponseData(realm string, type_ PbsTypeEnum) *ConfigAccessGetPamResponseData {
	this := ConfigAccessGetPamResponseData{}
	var default_ bool = 0
	this.Default = &default_
	this.Realm = realm
	this.Type = type_
	return &this
}

// NewConfigAccessGetPamResponseDataWithDefaults instantiates a new ConfigAccessGetPamResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigAccessGetPamResponseDataWithDefaults() *ConfigAccessGetPamResponseData {
	this := ConfigAccessGetPamResponseData{}


	var default_ bool = 0
	this.Default = &default_



	return &this
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigAccessGetPamResponseData) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetPamResponseData) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigAccessGetPamResponseData) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigAccessGetPamResponseData) SetComment(v string) {
	o.Comment = &v
}


// GetDefault returns the Default field value if set, zero value otherwise.
func (o *ConfigAccessGetPamResponseData) GetDefault() bool {
	if o == nil || IsNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetPamResponseData) GetDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *ConfigAccessGetPamResponseData) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *ConfigAccessGetPamResponseData) SetDefault(v bool) {
	o.Default = &v
}


// GetRealm returns the Realm field value
func (o *ConfigAccessGetPamResponseData) GetRealm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Realm
}

// GetRealmOk returns a tuple with the Realm field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetPamResponseData) GetRealmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Realm, true
}

// SetRealm sets field value
func (o *ConfigAccessGetPamResponseData) SetRealm(v string) {
	o.Realm = v
}


// GetType returns the Type field value
func (o *ConfigAccessGetPamResponseData) GetType() PbsTypeEnum {
	if o == nil {
		var ret PbsTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConfigAccessGetPamResponseData) GetTypeOk() (*PbsTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConfigAccessGetPamResponseData) SetType(v PbsTypeEnum) {
	o.Type = v
}


func (o ConfigAccessGetPamResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigAccessGetPamResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	
	toSerialize["realm"] = o.Realm
	
	toSerialize["type"] = o.Type
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigAccessGetPamResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"realm",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigAccessGetPamResponseData := _ConfigAccessGetPamResponseData{}

	err = json.Unmarshal(data, &varConfigAccessGetPamResponseData)

	if err != nil {
		return err
	}

	*o = ConfigAccessGetPamResponseData(varConfigAccessGetPamResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "comment")
		delete(additionalProperties, "default")
		delete(additionalProperties, "realm")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigAccessGetPamResponseData struct {
	value *ConfigAccessGetPamResponseData
	isSet bool
}

func (v NullableConfigAccessGetPamResponseData) Get() *ConfigAccessGetPamResponseData {
	return v.value
}

func (v *NullableConfigAccessGetPamResponseData) Set(val *ConfigAccessGetPamResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigAccessGetPamResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigAccessGetPamResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigAccessGetPamResponseData(val *ConfigAccessGetPamResponseData) *NullableConfigAccessGetPamResponseData {
	return &NullableConfigAccessGetPamResponseData{value: val, isSet: true}
}

func (v NullableConfigAccessGetPamResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigAccessGetPamResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


