/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsBackupTypeEnum the model 'PbsBackupTypeEnum'
type PbsBackupTypeEnum string

// List of PbsBackupTypeEnum
const (
	PBSBACKUPTYPEENUM_VM PbsBackupTypeEnum = "vm"
	PBSBACKUPTYPEENUM_CT PbsBackupTypeEnum = "ct"
	PBSBACKUPTYPEENUM_HOST PbsBackupTypeEnum = "host"
)

// All allowed values of PbsBackupTypeEnum enum
var AllowedPbsBackupTypeEnumEnumValues = []PbsBackupTypeEnum{
	"vm",
	"ct",
	"host",
}

func (v *PbsBackupTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsBackupTypeEnum(value)
	for _, existing := range AllowedPbsBackupTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsBackupTypeEnum", value)
}

// NewPbsBackupTypeEnumFromValue returns a pointer to a valid PbsBackupTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsBackupTypeEnumFromValue(v string) (*PbsBackupTypeEnum, error) {
	ev := PbsBackupTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsBackupTypeEnum: valid values are %v", v, AllowedPbsBackupTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsBackupTypeEnum) IsValid() bool {
	for _, existing := range AllowedPbsBackupTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsBackupTypeEnum value
func (v PbsBackupTypeEnum) Ptr() *PbsBackupTypeEnum {
	return &v
}

type NullablePbsBackupTypeEnum struct {
	value *PbsBackupTypeEnum
	isSet bool
}

func (v NullablePbsBackupTypeEnum) Get() *PbsBackupTypeEnum {
	return v.value
}

func (v *NullablePbsBackupTypeEnum) Set(val *PbsBackupTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsBackupTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsBackupTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsBackupTypeEnum(val *PbsBackupTypeEnum) *NullablePbsBackupTypeEnum {
	return &NullablePbsBackupTypeEnum{value: val, isSet: true}
}

func (v NullablePbsBackupTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsBackupTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

