/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackupUpgradeCreateBlobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupUpgradeCreateBlobRequest{}

// BackupUpgradeCreateBlobRequest struct for BackupUpgradeCreateBlobRequest
type BackupUpgradeCreateBlobRequest struct {

	// Encoded blob size.
	EncodedSize int32 `json:"encoded-size"`

	// Backup archive name.
	FileName string `json:"file-name" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

}

type _BackupUpgradeCreateBlobRequest BackupUpgradeCreateBlobRequest

// NewBackupUpgradeCreateBlobRequest instantiates a new BackupUpgradeCreateBlobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupUpgradeCreateBlobRequest(encodedSize int32, fileName string) *BackupUpgradeCreateBlobRequest {
	this := BackupUpgradeCreateBlobRequest{}
	this.EncodedSize = encodedSize
	this.FileName = fileName
	return &this
}

// NewBackupUpgradeCreateBlobRequestWithDefaults instantiates a new BackupUpgradeCreateBlobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupUpgradeCreateBlobRequestWithDefaults() *BackupUpgradeCreateBlobRequest {
	this := BackupUpgradeCreateBlobRequest{}



	return &this
}


// GetEncodedSize returns the EncodedSize field value
func (o *BackupUpgradeCreateBlobRequest) GetEncodedSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EncodedSize
}

// GetEncodedSizeOk returns a tuple with the EncodedSize field value
// and a boolean to check if the value has been set.
func (o *BackupUpgradeCreateBlobRequest) GetEncodedSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncodedSize, true
}

// SetEncodedSize sets field value
func (o *BackupUpgradeCreateBlobRequest) SetEncodedSize(v int32) {
	o.EncodedSize = v
}


// GetFileName returns the FileName field value
func (o *BackupUpgradeCreateBlobRequest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *BackupUpgradeCreateBlobRequest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *BackupUpgradeCreateBlobRequest) SetFileName(v string) {
	o.FileName = v
}


func (o BackupUpgradeCreateBlobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupUpgradeCreateBlobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["encoded-size"] = o.EncodedSize
	
	toSerialize["file-name"] = o.FileName
	
	return toSerialize, nil
}

func (o *BackupUpgradeCreateBlobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"encoded-size",
		"file-name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupUpgradeCreateBlobRequest := _BackupUpgradeCreateBlobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupUpgradeCreateBlobRequest)

	if err != nil {
		return err
	}

	*o = BackupUpgradeCreateBlobRequest(varBackupUpgradeCreateBlobRequest)

	return err
}

type NullableBackupUpgradeCreateBlobRequest struct {
	value *BackupUpgradeCreateBlobRequest
	isSet bool
}

func (v NullableBackupUpgradeCreateBlobRequest) Get() *BackupUpgradeCreateBlobRequest {
	return v.value
}

func (v *NullableBackupUpgradeCreateBlobRequest) Set(val *BackupUpgradeCreateBlobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupUpgradeCreateBlobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupUpgradeCreateBlobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupUpgradeCreateBlobRequest(val *BackupUpgradeCreateBlobRequest) *NullableBackupUpgradeCreateBlobRequest {
	return &NullableBackupUpgradeCreateBlobRequest{value: val, isSet: true}
}

func (v NullableBackupUpgradeCreateBlobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupUpgradeCreateBlobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


