/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsFilesystemEnum the model 'PbsFilesystemEnum'
type PbsFilesystemEnum string

// List of PbsFilesystemEnum
const (
	PBSFILESYSTEMENUM_EXT4 PbsFilesystemEnum = "ext4"
	PBSFILESYSTEMENUM_XFS PbsFilesystemEnum = "xfs"
)

// All allowed values of PbsFilesystemEnum enum
var AllowedPbsFilesystemEnumEnumValues = []PbsFilesystemEnum{
	"ext4",
	"xfs",
}

func (v *PbsFilesystemEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsFilesystemEnum(value)
	for _, existing := range AllowedPbsFilesystemEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsFilesystemEnum", value)
}

// NewPbsFilesystemEnumFromValue returns a pointer to a valid PbsFilesystemEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsFilesystemEnumFromValue(v string) (*PbsFilesystemEnum, error) {
	ev := PbsFilesystemEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsFilesystemEnum: valid values are %v", v, AllowedPbsFilesystemEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsFilesystemEnum) IsValid() bool {
	for _, existing := range AllowedPbsFilesystemEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsFilesystemEnum value
func (v PbsFilesystemEnum) Ptr() *PbsFilesystemEnum {
	return &v
}

type NullablePbsFilesystemEnum struct {
	value *PbsFilesystemEnum
	isSet bool
}

func (v NullablePbsFilesystemEnum) Get() *PbsFilesystemEnum {
	return v.value
}

func (v *NullablePbsFilesystemEnum) Set(val *PbsFilesystemEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsFilesystemEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsFilesystemEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsFilesystemEnum(val *PbsFilesystemEnum) *NullablePbsFilesystemEnum {
	return &NullablePbsFilesystemEnum{value: val, isSet: true}
}

func (v NullablePbsFilesystemEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsFilesystemEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

