/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackupUpgradeCreateFixedIndexRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupUpgradeCreateFixedIndexRequest{}

// BackupUpgradeCreateFixedIndexRequest struct for BackupUpgradeCreateFixedIndexRequest
type BackupUpgradeCreateFixedIndexRequest struct {

	// Backup archive name.
	ArchiveName string `json:"archive-name" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// If set, compare last backup's csum and reuse index for incremental backup if it matches.
	ReuseCsum *string `json:"reuse-csum,omitempty"`

	// File size.
	Size *int64 `json:"size,omitempty"`

}

type _BackupUpgradeCreateFixedIndexRequest BackupUpgradeCreateFixedIndexRequest

// NewBackupUpgradeCreateFixedIndexRequest instantiates a new BackupUpgradeCreateFixedIndexRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupUpgradeCreateFixedIndexRequest(archiveName string) *BackupUpgradeCreateFixedIndexRequest {
	this := BackupUpgradeCreateFixedIndexRequest{}
	this.ArchiveName = archiveName
	return &this
}

// NewBackupUpgradeCreateFixedIndexRequestWithDefaults instantiates a new BackupUpgradeCreateFixedIndexRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupUpgradeCreateFixedIndexRequestWithDefaults() *BackupUpgradeCreateFixedIndexRequest {
	this := BackupUpgradeCreateFixedIndexRequest{}




	return &this
}


// GetArchiveName returns the ArchiveName field value
func (o *BackupUpgradeCreateFixedIndexRequest) GetArchiveName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArchiveName
}

// GetArchiveNameOk returns a tuple with the ArchiveName field value
// and a boolean to check if the value has been set.
func (o *BackupUpgradeCreateFixedIndexRequest) GetArchiveNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArchiveName, true
}

// SetArchiveName sets field value
func (o *BackupUpgradeCreateFixedIndexRequest) SetArchiveName(v string) {
	o.ArchiveName = v
}


// GetReuseCsum returns the ReuseCsum field value if set, zero value otherwise.
func (o *BackupUpgradeCreateFixedIndexRequest) GetReuseCsum() string {
	if o == nil || IsNil(o.ReuseCsum) {
		var ret string
		return ret
	}
	return *o.ReuseCsum
}

// GetReuseCsumOk returns a tuple with the ReuseCsum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupUpgradeCreateFixedIndexRequest) GetReuseCsumOk() (*string, bool) {
	if o == nil || IsNil(o.ReuseCsum) {
		return nil, false
	}
	return o.ReuseCsum, true
}

// HasReuseCsum returns a boolean if a field has been set.
func (o *BackupUpgradeCreateFixedIndexRequest) HasReuseCsum() bool {
	if o != nil && !IsNil(o.ReuseCsum) {
		return true
	}

	return false
}

// SetReuseCsum gets a reference to the given string and assigns it to the ReuseCsum field.
func (o *BackupUpgradeCreateFixedIndexRequest) SetReuseCsum(v string) {
	o.ReuseCsum = &v
}


// GetSize returns the Size field value if set, zero value otherwise.
func (o *BackupUpgradeCreateFixedIndexRequest) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupUpgradeCreateFixedIndexRequest) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *BackupUpgradeCreateFixedIndexRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *BackupUpgradeCreateFixedIndexRequest) SetSize(v int64) {
	o.Size = &v
}


func (o BackupUpgradeCreateFixedIndexRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupUpgradeCreateFixedIndexRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["archive-name"] = o.ArchiveName
	
	if !IsNil(o.ReuseCsum) {
		toSerialize["reuse-csum"] = o.ReuseCsum
	}
	
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	
	return toSerialize, nil
}

func (o *BackupUpgradeCreateFixedIndexRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"archive-name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupUpgradeCreateFixedIndexRequest := _BackupUpgradeCreateFixedIndexRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupUpgradeCreateFixedIndexRequest)

	if err != nil {
		return err
	}

	*o = BackupUpgradeCreateFixedIndexRequest(varBackupUpgradeCreateFixedIndexRequest)

	return err
}

type NullableBackupUpgradeCreateFixedIndexRequest struct {
	value *BackupUpgradeCreateFixedIndexRequest
	isSet bool
}

func (v NullableBackupUpgradeCreateFixedIndexRequest) Get() *BackupUpgradeCreateFixedIndexRequest {
	return v.value
}

func (v *NullableBackupUpgradeCreateFixedIndexRequest) Set(val *BackupUpgradeCreateFixedIndexRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupUpgradeCreateFixedIndexRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupUpgradeCreateFixedIndexRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupUpgradeCreateFixedIndexRequest(val *BackupUpgradeCreateFixedIndexRequest) *NullableBackupUpgradeCreateFixedIndexRequest {
	return &NullableBackupUpgradeCreateFixedIndexRequest{value: val, isSet: true}
}

func (v NullableBackupUpgradeCreateFixedIndexRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupUpgradeCreateFixedIndexRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


