/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsNodesStatusCommandEnum the model 'PbsNodesStatusCommandEnum'
type PbsNodesStatusCommandEnum string

// List of PbsNodesStatusCommandEnum
const (
	PBSNODESSTATUSCOMMANDENUM_REBOOT PbsNodesStatusCommandEnum = "reboot"
	PBSNODESSTATUSCOMMANDENUM_SHUTDOWN PbsNodesStatusCommandEnum = "shutdown"
)

// All allowed values of PbsNodesStatusCommandEnum enum
var AllowedPbsNodesStatusCommandEnumEnumValues = []PbsNodesStatusCommandEnum{
	"reboot",
	"shutdown",
}

func (v *PbsNodesStatusCommandEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsNodesStatusCommandEnum(value)
	for _, existing := range AllowedPbsNodesStatusCommandEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsNodesStatusCommandEnum", value)
}

// NewPbsNodesStatusCommandEnumFromValue returns a pointer to a valid PbsNodesStatusCommandEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsNodesStatusCommandEnumFromValue(v string) (*PbsNodesStatusCommandEnum, error) {
	ev := PbsNodesStatusCommandEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsNodesStatusCommandEnum: valid values are %v", v, AllowedPbsNodesStatusCommandEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsNodesStatusCommandEnum) IsValid() bool {
	for _, existing := range AllowedPbsNodesStatusCommandEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsNodesStatusCommandEnum value
func (v PbsNodesStatusCommandEnum) Ptr() *PbsNodesStatusCommandEnum {
	return &v
}

type NullablePbsNodesStatusCommandEnum struct {
	value *PbsNodesStatusCommandEnum
	isSet bool
}

func (v NullablePbsNodesStatusCommandEnum) Get() *PbsNodesStatusCommandEnum {
	return v.value
}

func (v *NullablePbsNodesStatusCommandEnum) Set(val *PbsNodesStatusCommandEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsNodesStatusCommandEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsNodesStatusCommandEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsNodesStatusCommandEnum(val *PbsNodesStatusCommandEnum) *NullablePbsNodesStatusCommandEnum {
	return &NullablePbsNodesStatusCommandEnum{value: val, isSet: true}
}

func (v NullablePbsNodesStatusCommandEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsNodesStatusCommandEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

