/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigTrafficControlGetTrafficControlResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigTrafficControlGetTrafficControlResponseDataInner{}

// ConfigTrafficControlGetTrafficControlResponseDataInner struct for ConfigTrafficControlGetTrafficControlResponseDataInner
type ConfigTrafficControlGetTrafficControlResponseDataInner struct {

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstIn *string `json:"burst-in,omitempty"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstOut *string `json:"burst-out,omitempty"`

	// Comment.
	Comment *string `json:"comment,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// Rule ID.
	Name string `json:"name" validate:"regexp=^(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

	// Rule applies to Source IPs within this networks
	Network []string `json:"network"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateIn *string `json:"rate-in,omitempty"`

	// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateOut *string `json:"rate-out,omitempty"`

	// Enable the rule at specific times
	Timeframe []string `json:"timeframe,omitempty"`

	// Rule applies to authenticated API requests of any of these users (overrides IP-only rules)
	Users []string `json:"users,omitempty"`

	AdditionalProperties map[string]interface{}
}

type _ConfigTrafficControlGetTrafficControlResponseDataInner ConfigTrafficControlGetTrafficControlResponseDataInner

// NewConfigTrafficControlGetTrafficControlResponseDataInner instantiates a new ConfigTrafficControlGetTrafficControlResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigTrafficControlGetTrafficControlResponseDataInner(name string, network []string) *ConfigTrafficControlGetTrafficControlResponseDataInner {
	this := ConfigTrafficControlGetTrafficControlResponseDataInner{}
	this.Name = name
	this.Network = network
	return &this
}

// NewConfigTrafficControlGetTrafficControlResponseDataInnerWithDefaults instantiates a new ConfigTrafficControlGetTrafficControlResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigTrafficControlGetTrafficControlResponseDataInnerWithDefaults() *ConfigTrafficControlGetTrafficControlResponseDataInner {
	this := ConfigTrafficControlGetTrafficControlResponseDataInner{}










	return &this
}


// GetBurstIn returns the BurstIn field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetBurstIn() string {
	if o == nil || IsNil(o.BurstIn) {
		var ret string
		return ret
	}
	return *o.BurstIn
}

// GetBurstInOk returns a tuple with the BurstIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetBurstInOk() (*string, bool) {
	if o == nil || IsNil(o.BurstIn) {
		return nil, false
	}
	return o.BurstIn, true
}

// HasBurstIn returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasBurstIn() bool {
	if o != nil && !IsNil(o.BurstIn) {
		return true
	}

	return false
}

// SetBurstIn gets a reference to the given string and assigns it to the BurstIn field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetBurstIn(v string) {
	o.BurstIn = &v
}


// GetBurstOut returns the BurstOut field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetBurstOut() string {
	if o == nil || IsNil(o.BurstOut) {
		var ret string
		return ret
	}
	return *o.BurstOut
}

// GetBurstOutOk returns a tuple with the BurstOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetBurstOutOk() (*string, bool) {
	if o == nil || IsNil(o.BurstOut) {
		return nil, false
	}
	return o.BurstOut, true
}

// HasBurstOut returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasBurstOut() bool {
	if o != nil && !IsNil(o.BurstOut) {
		return true
	}

	return false
}

// SetBurstOut gets a reference to the given string and assigns it to the BurstOut field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetBurstOut(v string) {
	o.BurstOut = &v
}


// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetComment(v string) {
	o.Comment = &v
}


// GetName returns the Name field value
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetName(v string) {
	o.Name = v
}


// GetNetwork returns the Network field value
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetNetwork() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetNetworkOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Network, true
}

// SetNetwork sets field value
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetNetwork(v []string) {
	o.Network = v
}


// GetRateIn returns the RateIn field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetRateIn() string {
	if o == nil || IsNil(o.RateIn) {
		var ret string
		return ret
	}
	return *o.RateIn
}

// GetRateInOk returns a tuple with the RateIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetRateInOk() (*string, bool) {
	if o == nil || IsNil(o.RateIn) {
		return nil, false
	}
	return o.RateIn, true
}

// HasRateIn returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasRateIn() bool {
	if o != nil && !IsNil(o.RateIn) {
		return true
	}

	return false
}

// SetRateIn gets a reference to the given string and assigns it to the RateIn field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetRateIn(v string) {
	o.RateIn = &v
}


// GetRateOut returns the RateOut field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetRateOut() string {
	if o == nil || IsNil(o.RateOut) {
		var ret string
		return ret
	}
	return *o.RateOut
}

// GetRateOutOk returns a tuple with the RateOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetRateOutOk() (*string, bool) {
	if o == nil || IsNil(o.RateOut) {
		return nil, false
	}
	return o.RateOut, true
}

// HasRateOut returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasRateOut() bool {
	if o != nil && !IsNil(o.RateOut) {
		return true
	}

	return false
}

// SetRateOut gets a reference to the given string and assigns it to the RateOut field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetRateOut(v string) {
	o.RateOut = &v
}


// GetTimeframe returns the Timeframe field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetTimeframe() []string {
	if o == nil || IsNil(o.Timeframe) {
		var ret []string
		return ret
	}
	return o.Timeframe
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetTimeframeOk() ([]string, bool) {
	if o == nil || IsNil(o.Timeframe) {
		return nil, false
	}
	return o.Timeframe, true
}

// HasTimeframe returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasTimeframe() bool {
	if o != nil && !IsNil(o.Timeframe) {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given []string and assigns it to the Timeframe field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetTimeframe(v []string) {
	o.Timeframe = v
}


// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) SetUsers(v []string) {
	o.Users = v
}


func (o ConfigTrafficControlGetTrafficControlResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigTrafficControlGetTrafficControlResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.BurstIn) {
		toSerialize["burst-in"] = o.BurstIn
	}
	
	if !IsNil(o.BurstOut) {
		toSerialize["burst-out"] = o.BurstOut
	}
	
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	
	toSerialize["name"] = o.Name
	
	toSerialize["network"] = o.Network
	
	if !IsNil(o.RateIn) {
		toSerialize["rate-in"] = o.RateIn
	}
	
	if !IsNil(o.RateOut) {
		toSerialize["rate-out"] = o.RateOut
	}
	
	if !IsNil(o.Timeframe) {
		toSerialize["timeframe"] = o.Timeframe
	}
	
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigTrafficControlGetTrafficControlResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigTrafficControlGetTrafficControlResponseDataInner := _ConfigTrafficControlGetTrafficControlResponseDataInner{}

	err = json.Unmarshal(data, &varConfigTrafficControlGetTrafficControlResponseDataInner)

	if err != nil {
		return err
	}

	*o = ConfigTrafficControlGetTrafficControlResponseDataInner(varConfigTrafficControlGetTrafficControlResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "burst-in")
		delete(additionalProperties, "burst-out")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "name")
		delete(additionalProperties, "network")
		delete(additionalProperties, "rate-in")
		delete(additionalProperties, "rate-out")
		delete(additionalProperties, "timeframe")
		delete(additionalProperties, "users")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigTrafficControlGetTrafficControlResponseDataInner struct {
	value *ConfigTrafficControlGetTrafficControlResponseDataInner
	isSet bool
}

func (v NullableConfigTrafficControlGetTrafficControlResponseDataInner) Get() *ConfigTrafficControlGetTrafficControlResponseDataInner {
	return v.value
}

func (v *NullableConfigTrafficControlGetTrafficControlResponseDataInner) Set(val *ConfigTrafficControlGetTrafficControlResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigTrafficControlGetTrafficControlResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigTrafficControlGetTrafficControlResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigTrafficControlGetTrafficControlResponseDataInner(val *ConfigTrafficControlGetTrafficControlResponseDataInner) *NullableConfigTrafficControlGetTrafficControlResponseDataInner {
	return &NullableConfigTrafficControlGetTrafficControlResponseDataInner{value: val, isSet: true}
}

func (v NullableConfigTrafficControlGetTrafficControlResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigTrafficControlGetTrafficControlResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


