/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccessUpdatePasswordRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessUpdatePasswordRequest{}

// AccessUpdatePasswordRequest struct for AccessUpdatePasswordRequest
type AccessUpdatePasswordRequest struct {

	// The current password for confirmation, unless logged in as root@pam
	ConfirmationPassword *string `json:"confirmation-password,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// User Password.
	Password string `json:"password" validate:"regexp=^[[:^cntrl:]]*$"`

	// User ID
	Userid string `json:"userid" validate:"regexp=^(?:[^\\\\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)$"`

}

type _AccessUpdatePasswordRequest AccessUpdatePasswordRequest

// NewAccessUpdatePasswordRequest instantiates a new AccessUpdatePasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessUpdatePasswordRequest(password string, userid string) *AccessUpdatePasswordRequest {
	this := AccessUpdatePasswordRequest{}
	this.Password = password
	this.Userid = userid
	return &this
}

// NewAccessUpdatePasswordRequestWithDefaults instantiates a new AccessUpdatePasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessUpdatePasswordRequestWithDefaults() *AccessUpdatePasswordRequest {
	this := AccessUpdatePasswordRequest{}




	return &this
}


// GetConfirmationPassword returns the ConfirmationPassword field value if set, zero value otherwise.
func (o *AccessUpdatePasswordRequest) GetConfirmationPassword() string {
	if o == nil || IsNil(o.ConfirmationPassword) {
		var ret string
		return ret
	}
	return *o.ConfirmationPassword
}

// GetConfirmationPasswordOk returns a tuple with the ConfirmationPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessUpdatePasswordRequest) GetConfirmationPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmationPassword) {
		return nil, false
	}
	return o.ConfirmationPassword, true
}

// HasConfirmationPassword returns a boolean if a field has been set.
func (o *AccessUpdatePasswordRequest) HasConfirmationPassword() bool {
	if o != nil && !IsNil(o.ConfirmationPassword) {
		return true
	}

	return false
}

// SetConfirmationPassword gets a reference to the given string and assigns it to the ConfirmationPassword field.
func (o *AccessUpdatePasswordRequest) SetConfirmationPassword(v string) {
	o.ConfirmationPassword = &v
}


// GetPassword returns the Password field value
func (o *AccessUpdatePasswordRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AccessUpdatePasswordRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AccessUpdatePasswordRequest) SetPassword(v string) {
	o.Password = v
}


// GetUserid returns the Userid field value
func (o *AccessUpdatePasswordRequest) GetUserid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userid
}

// GetUseridOk returns a tuple with the Userid field value
// and a boolean to check if the value has been set.
func (o *AccessUpdatePasswordRequest) GetUseridOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userid, true
}

// SetUserid sets field value
func (o *AccessUpdatePasswordRequest) SetUserid(v string) {
	o.Userid = v
}


func (o AccessUpdatePasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessUpdatePasswordRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.ConfirmationPassword) {
		toSerialize["confirmation-password"] = o.ConfirmationPassword
	}
	
	toSerialize["password"] = o.Password
	
	toSerialize["userid"] = o.Userid
	
	return toSerialize, nil
}

func (o *AccessUpdatePasswordRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
		"userid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessUpdatePasswordRequest := _AccessUpdatePasswordRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessUpdatePasswordRequest)

	if err != nil {
		return err
	}

	*o = AccessUpdatePasswordRequest(varAccessUpdatePasswordRequest)

	return err
}

type NullableAccessUpdatePasswordRequest struct {
	value *AccessUpdatePasswordRequest
	isSet bool
}

func (v NullableAccessUpdatePasswordRequest) Get() *AccessUpdatePasswordRequest {
	return v.value
}

func (v *NullableAccessUpdatePasswordRequest) Set(val *AccessUpdatePasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessUpdatePasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessUpdatePasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessUpdatePasswordRequest(val *AccessUpdatePasswordRequest) *NullableAccessUpdatePasswordRequest {
	return &NullableAccessUpdatePasswordRequest{value: val, isSet: true}
}

func (v NullableAccessUpdatePasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessUpdatePasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


