/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TapeMediaGetListResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TapeMediaGetListResponseDataInner{}

// TapeMediaGetListResponseDataInner struct for TapeMediaGetListResponseDataInner
type TapeMediaGetListResponseDataInner struct {

	// Bytes currently used
	BytesUsed *int64 `json:"bytes-used,omitempty"`

	// Catalog status OK
	Catalog bool `json:"catalog"`

	// Creation time stamp
	Ctime int64 `json:"ctime"`

	// Expired flag
	Expired bool `json:"expired"`

	// Media label text (or Barcode)
	LabelText string `json:"label-text"`

	// Media location (e.g. 'offline', 'online-<changer_name>', 'vault-<vault_name>')
	Location string `json:"location"`

	// MediaSet creation time stamp
	MediaSetCtime *int64 `json:"media-set-ctime,omitempty"`

	// Media set name
	MediaSetName *string `json:"media-set-name,omitempty"`

	// MediaSet Uuid (We use the all-zero Uuid to reserve an empty media for a specific pool).
	MediaSetUuid *string `json:"media-set-uuid,omitempty" validate:"regexp=^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"`

	// Media Pool
	Pool *string `json:"pool,omitempty"`

	// Media set seq_nr
	SeqNr *int64 `json:"seq-nr,omitempty"`

	// Media status Media Status
	Status PbsTapeMediaStatusEnum `json:"status"`

	// Media Uuid.
	Uuid string `json:"uuid" validate:"regexp=^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"`

	AdditionalProperties map[string]interface{}
}

type _TapeMediaGetListResponseDataInner TapeMediaGetListResponseDataInner

// NewTapeMediaGetListResponseDataInner instantiates a new TapeMediaGetListResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTapeMediaGetListResponseDataInner(catalog bool, ctime int64, expired bool, labelText string, location string, status PbsTapeMediaStatusEnum, uuid string) *TapeMediaGetListResponseDataInner {
	this := TapeMediaGetListResponseDataInner{}
	this.Catalog = catalog
	this.Ctime = ctime
	this.Expired = expired
	this.LabelText = labelText
	this.Location = location
	this.Status = status
	this.Uuid = uuid
	return &this
}

// NewTapeMediaGetListResponseDataInnerWithDefaults instantiates a new TapeMediaGetListResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTapeMediaGetListResponseDataInnerWithDefaults() *TapeMediaGetListResponseDataInner {
	this := TapeMediaGetListResponseDataInner{}














	return &this
}


// GetBytesUsed returns the BytesUsed field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetBytesUsed() int64 {
	if o == nil || IsNil(o.BytesUsed) {
		var ret int64
		return ret
	}
	return *o.BytesUsed
}

// GetBytesUsedOk returns a tuple with the BytesUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetBytesUsedOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesUsed) {
		return nil, false
	}
	return o.BytesUsed, true
}

// HasBytesUsed returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasBytesUsed() bool {
	if o != nil && !IsNil(o.BytesUsed) {
		return true
	}

	return false
}

// SetBytesUsed gets a reference to the given int64 and assigns it to the BytesUsed field.
func (o *TapeMediaGetListResponseDataInner) SetBytesUsed(v int64) {
	o.BytesUsed = &v
}


// GetCatalog returns the Catalog field value
func (o *TapeMediaGetListResponseDataInner) GetCatalog() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Catalog
}

// GetCatalogOk returns a tuple with the Catalog field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetCatalogOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Catalog, true
}

// SetCatalog sets field value
func (o *TapeMediaGetListResponseDataInner) SetCatalog(v bool) {
	o.Catalog = v
}


// GetCtime returns the Ctime field value
func (o *TapeMediaGetListResponseDataInner) GetCtime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ctime
}

// GetCtimeOk returns a tuple with the Ctime field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetCtimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ctime, true
}

// SetCtime sets field value
func (o *TapeMediaGetListResponseDataInner) SetCtime(v int64) {
	o.Ctime = v
}


// GetExpired returns the Expired field value
func (o *TapeMediaGetListResponseDataInner) GetExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expired, true
}

// SetExpired sets field value
func (o *TapeMediaGetListResponseDataInner) SetExpired(v bool) {
	o.Expired = v
}


// GetLabelText returns the LabelText field value
func (o *TapeMediaGetListResponseDataInner) GetLabelText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LabelText
}

// GetLabelTextOk returns a tuple with the LabelText field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetLabelTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelText, true
}

// SetLabelText sets field value
func (o *TapeMediaGetListResponseDataInner) SetLabelText(v string) {
	o.LabelText = v
}


// GetLocation returns the Location field value
func (o *TapeMediaGetListResponseDataInner) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *TapeMediaGetListResponseDataInner) SetLocation(v string) {
	o.Location = v
}


// GetMediaSetCtime returns the MediaSetCtime field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetCtime() int64 {
	if o == nil || IsNil(o.MediaSetCtime) {
		var ret int64
		return ret
	}
	return *o.MediaSetCtime
}

// GetMediaSetCtimeOk returns a tuple with the MediaSetCtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetCtimeOk() (*int64, bool) {
	if o == nil || IsNil(o.MediaSetCtime) {
		return nil, false
	}
	return o.MediaSetCtime, true
}

// HasMediaSetCtime returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasMediaSetCtime() bool {
	if o != nil && !IsNil(o.MediaSetCtime) {
		return true
	}

	return false
}

// SetMediaSetCtime gets a reference to the given int64 and assigns it to the MediaSetCtime field.
func (o *TapeMediaGetListResponseDataInner) SetMediaSetCtime(v int64) {
	o.MediaSetCtime = &v
}


// GetMediaSetName returns the MediaSetName field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetName() string {
	if o == nil || IsNil(o.MediaSetName) {
		var ret string
		return ret
	}
	return *o.MediaSetName
}

// GetMediaSetNameOk returns a tuple with the MediaSetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetNameOk() (*string, bool) {
	if o == nil || IsNil(o.MediaSetName) {
		return nil, false
	}
	return o.MediaSetName, true
}

// HasMediaSetName returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasMediaSetName() bool {
	if o != nil && !IsNil(o.MediaSetName) {
		return true
	}

	return false
}

// SetMediaSetName gets a reference to the given string and assigns it to the MediaSetName field.
func (o *TapeMediaGetListResponseDataInner) SetMediaSetName(v string) {
	o.MediaSetName = &v
}


// GetMediaSetUuid returns the MediaSetUuid field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetUuid() string {
	if o == nil || IsNil(o.MediaSetUuid) {
		var ret string
		return ret
	}
	return *o.MediaSetUuid
}

// GetMediaSetUuidOk returns a tuple with the MediaSetUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetMediaSetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.MediaSetUuid) {
		return nil, false
	}
	return o.MediaSetUuid, true
}

// HasMediaSetUuid returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasMediaSetUuid() bool {
	if o != nil && !IsNil(o.MediaSetUuid) {
		return true
	}

	return false
}

// SetMediaSetUuid gets a reference to the given string and assigns it to the MediaSetUuid field.
func (o *TapeMediaGetListResponseDataInner) SetMediaSetUuid(v string) {
	o.MediaSetUuid = &v
}


// GetPool returns the Pool field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetPool() string {
	if o == nil || IsNil(o.Pool) {
		var ret string
		return ret
	}
	return *o.Pool
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetPoolOk() (*string, bool) {
	if o == nil || IsNil(o.Pool) {
		return nil, false
	}
	return o.Pool, true
}

// HasPool returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasPool() bool {
	if o != nil && !IsNil(o.Pool) {
		return true
	}

	return false
}

// SetPool gets a reference to the given string and assigns it to the Pool field.
func (o *TapeMediaGetListResponseDataInner) SetPool(v string) {
	o.Pool = &v
}


// GetSeqNr returns the SeqNr field value if set, zero value otherwise.
func (o *TapeMediaGetListResponseDataInner) GetSeqNr() int64 {
	if o == nil || IsNil(o.SeqNr) {
		var ret int64
		return ret
	}
	return *o.SeqNr
}

// GetSeqNrOk returns a tuple with the SeqNr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetSeqNrOk() (*int64, bool) {
	if o == nil || IsNil(o.SeqNr) {
		return nil, false
	}
	return o.SeqNr, true
}

// HasSeqNr returns a boolean if a field has been set.
func (o *TapeMediaGetListResponseDataInner) HasSeqNr() bool {
	if o != nil && !IsNil(o.SeqNr) {
		return true
	}

	return false
}

// SetSeqNr gets a reference to the given int64 and assigns it to the SeqNr field.
func (o *TapeMediaGetListResponseDataInner) SetSeqNr(v int64) {
	o.SeqNr = &v
}


// GetStatus returns the Status field value
func (o *TapeMediaGetListResponseDataInner) GetStatus() PbsTapeMediaStatusEnum {
	if o == nil {
		var ret PbsTapeMediaStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetStatusOk() (*PbsTapeMediaStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TapeMediaGetListResponseDataInner) SetStatus(v PbsTapeMediaStatusEnum) {
	o.Status = v
}


// GetUuid returns the Uuid field value
func (o *TapeMediaGetListResponseDataInner) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TapeMediaGetListResponseDataInner) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TapeMediaGetListResponseDataInner) SetUuid(v string) {
	o.Uuid = v
}


func (o TapeMediaGetListResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TapeMediaGetListResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.BytesUsed) {
		toSerialize["bytes-used"] = o.BytesUsed
	}
	
	toSerialize["catalog"] = o.Catalog
	
	toSerialize["ctime"] = o.Ctime
	
	toSerialize["expired"] = o.Expired
	
	toSerialize["label-text"] = o.LabelText
	
	toSerialize["location"] = o.Location
	
	if !IsNil(o.MediaSetCtime) {
		toSerialize["media-set-ctime"] = o.MediaSetCtime
	}
	
	if !IsNil(o.MediaSetName) {
		toSerialize["media-set-name"] = o.MediaSetName
	}
	
	if !IsNil(o.MediaSetUuid) {
		toSerialize["media-set-uuid"] = o.MediaSetUuid
	}
	
	if !IsNil(o.Pool) {
		toSerialize["pool"] = o.Pool
	}
	
	if !IsNil(o.SeqNr) {
		toSerialize["seq-nr"] = o.SeqNr
	}
	
	toSerialize["status"] = o.Status
	
	toSerialize["uuid"] = o.Uuid
	

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TapeMediaGetListResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catalog",
		"ctime",
		"expired",
		"label-text",
		"location",
		"status",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTapeMediaGetListResponseDataInner := _TapeMediaGetListResponseDataInner{}

	err = json.Unmarshal(data, &varTapeMediaGetListResponseDataInner)

	if err != nil {
		return err
	}

	*o = TapeMediaGetListResponseDataInner(varTapeMediaGetListResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bytes-used")
		delete(additionalProperties, "catalog")
		delete(additionalProperties, "ctime")
		delete(additionalProperties, "expired")
		delete(additionalProperties, "label-text")
		delete(additionalProperties, "location")
		delete(additionalProperties, "media-set-ctime")
		delete(additionalProperties, "media-set-name")
		delete(additionalProperties, "media-set-uuid")
		delete(additionalProperties, "pool")
		delete(additionalProperties, "seq-nr")
		delete(additionalProperties, "status")
		delete(additionalProperties, "uuid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTapeMediaGetListResponseDataInner struct {
	value *TapeMediaGetListResponseDataInner
	isSet bool
}

func (v NullableTapeMediaGetListResponseDataInner) Get() *TapeMediaGetListResponseDataInner {
	return v.value
}

func (v *NullableTapeMediaGetListResponseDataInner) Set(val *TapeMediaGetListResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTapeMediaGetListResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTapeMediaGetListResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTapeMediaGetListResponseDataInner(val *TapeMediaGetListResponseDataInner) *NullableTapeMediaGetListResponseDataInner {
	return &NullableTapeMediaGetListResponseDataInner{value: val, isSet: true}
}

func (v NullableTapeMediaGetListResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTapeMediaGetListResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


