/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsDefaultLangEnum the model 'PbsDefaultLangEnum'
type PbsDefaultLangEnum string

// List of PbsDefaultLangEnum
const (
	PBSDEFAULTLANGENUM_AR PbsDefaultLangEnum = "ar"
	PBSDEFAULTLANGENUM_CA PbsDefaultLangEnum = "ca"
	PBSDEFAULTLANGENUM_DA PbsDefaultLangEnum = "da"
	PBSDEFAULTLANGENUM_DE PbsDefaultLangEnum = "de"
	PBSDEFAULTLANGENUM_EN PbsDefaultLangEnum = "en"
	PBSDEFAULTLANGENUM_ES PbsDefaultLangEnum = "es"
	PBSDEFAULTLANGENUM_EU PbsDefaultLangEnum = "eu"
	PBSDEFAULTLANGENUM_FA PbsDefaultLangEnum = "fa"
	PBSDEFAULTLANGENUM_FR PbsDefaultLangEnum = "fr"
	PBSDEFAULTLANGENUM_GL PbsDefaultLangEnum = "gl"
	PBSDEFAULTLANGENUM_HE PbsDefaultLangEnum = "he"
	PBSDEFAULTLANGENUM_HU PbsDefaultLangEnum = "hu"
	PBSDEFAULTLANGENUM_IT PbsDefaultLangEnum = "it"
	PBSDEFAULTLANGENUM_JA PbsDefaultLangEnum = "ja"
	PBSDEFAULTLANGENUM_KR PbsDefaultLangEnum = "kr"
	PBSDEFAULTLANGENUM_NB PbsDefaultLangEnum = "nb"
	PBSDEFAULTLANGENUM_NL PbsDefaultLangEnum = "nl"
	PBSDEFAULTLANGENUM_NN PbsDefaultLangEnum = "nn"
	PBSDEFAULTLANGENUM_PL PbsDefaultLangEnum = "pl"
	PBSDEFAULTLANGENUM_PT_BR PbsDefaultLangEnum = "pt_BR"
	PBSDEFAULTLANGENUM_RU PbsDefaultLangEnum = "ru"
	PBSDEFAULTLANGENUM_SL PbsDefaultLangEnum = "sl"
	PBSDEFAULTLANGENUM_SV PbsDefaultLangEnum = "sv"
	PBSDEFAULTLANGENUM_TR PbsDefaultLangEnum = "tr"
	PBSDEFAULTLANGENUM_ZH_CN PbsDefaultLangEnum = "zh_CN"
	PBSDEFAULTLANGENUM_ZH_TW PbsDefaultLangEnum = "zh_TW"
)

// All allowed values of PbsDefaultLangEnum enum
var AllowedPbsDefaultLangEnumEnumValues = []PbsDefaultLangEnum{
	"ar",
	"ca",
	"da",
	"de",
	"en",
	"es",
	"eu",
	"fa",
	"fr",
	"gl",
	"he",
	"hu",
	"it",
	"ja",
	"kr",
	"nb",
	"nl",
	"nn",
	"pl",
	"pt_BR",
	"ru",
	"sl",
	"sv",
	"tr",
	"zh_CN",
	"zh_TW",
}

func (v *PbsDefaultLangEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsDefaultLangEnum(value)
	for _, existing := range AllowedPbsDefaultLangEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsDefaultLangEnum", value)
}

// NewPbsDefaultLangEnumFromValue returns a pointer to a valid PbsDefaultLangEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsDefaultLangEnumFromValue(v string) (*PbsDefaultLangEnum, error) {
	ev := PbsDefaultLangEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsDefaultLangEnum: valid values are %v", v, AllowedPbsDefaultLangEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsDefaultLangEnum) IsValid() bool {
	for _, existing := range AllowedPbsDefaultLangEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsDefaultLangEnum value
func (v PbsDefaultLangEnum) Ptr() *PbsDefaultLangEnum {
	return &v
}

type NullablePbsDefaultLangEnum struct {
	value *PbsDefaultLangEnum
	isSet bool
}

func (v NullablePbsDefaultLangEnum) Get() *PbsDefaultLangEnum {
	return v.value
}

func (v *NullablePbsDefaultLangEnum) Set(val *PbsDefaultLangEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsDefaultLangEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsDefaultLangEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsDefaultLangEnum(val *PbsDefaultLangEnum) *NullablePbsDefaultLangEnum {
	return &NullablePbsDefaultLangEnum{value: val, isSet: true}
}

func (v NullablePbsDefaultLangEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsDefaultLangEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

