/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsKdfEnum the model 'PbsKdfEnum'
type PbsKdfEnum string

// List of PbsKdfEnum
const (
	PBSKDFENUM_NONE PbsKdfEnum = "none"
	PBSKDFENUM_SCRYPT PbsKdfEnum = "scrypt"
	PBSKDFENUM_PBKDF2 PbsKdfEnum = "pbkdf2"
)

// All allowed values of PbsKdfEnum enum
var AllowedPbsKdfEnumEnumValues = []PbsKdfEnum{
	"none",
	"scrypt",
	"pbkdf2",
}

func (v *PbsKdfEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsKdfEnum(value)
	for _, existing := range AllowedPbsKdfEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsKdfEnum", value)
}

// NewPbsKdfEnumFromValue returns a pointer to a valid PbsKdfEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsKdfEnumFromValue(v string) (*PbsKdfEnum, error) {
	ev := PbsKdfEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsKdfEnum: valid values are %v", v, AllowedPbsKdfEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsKdfEnum) IsValid() bool {
	for _, existing := range AllowedPbsKdfEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsKdfEnum value
func (v PbsKdfEnum) Ptr() *PbsKdfEnum {
	return &v
}

type NullablePbsKdfEnum struct {
	value *PbsKdfEnum
	isSet bool
}

func (v NullablePbsKdfEnum) Get() *PbsKdfEnum {
	return v.value
}

func (v *NullablePbsKdfEnum) Set(val *PbsKdfEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsKdfEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsKdfEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsKdfEnum(val *PbsKdfEnum) *NullablePbsKdfEnum {
	return &NullablePbsKdfEnum{value: val, isSet: true}
}

func (v NullablePbsKdfEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsKdfEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

