/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodesConfigUpdateConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodesConfigUpdateConfigRequest{}

// NodesConfigUpdateConfigRequest struct for NodesConfigUpdateConfigRequest
type NodesConfigUpdateConfigRequest struct {

	// The acme account to use on this node.
	Acme *PbsAcmeField `json:"acme,omitempty"`

	// ACME domain configuration string
	Acmedomain0 *PbsAcmedomainField `json:"acmedomain0,omitempty"`

	// ACME domain configuration string
	Acmedomain1 *PbsAcmedomainField `json:"acmedomain1,omitempty"`

	// ACME domain configuration string
	Acmedomain2 *PbsAcmedomainField `json:"acmedomain2,omitempty"`

	// ACME domain configuration string
	Acmedomain3 *PbsAcmedomainField `json:"acmedomain3,omitempty"`

	// ACME domain configuration string
	Acmedomain4 *PbsAcmedomainField `json:"acmedomain4,omitempty"`

	// OpenSSL cipher list used by the proxy for TLS <= 1.2
	CiphersTls12 *string `json:"ciphers-tls-1.2,omitempty" validate:"regexp=^[0-9A-Za-z_:, +!\\\\-@=.]+$"`

	// OpenSSL ciphersuites list used by the proxy for TLS 1.3
	CiphersTls13 *string `json:"ciphers-tls-1.3,omitempty" validate:"regexp=^[0-9A-Za-z_:, +!\\\\-@=.]+$"`

	// Consent banner text
	ConsentText *string `json:"consent-text,omitempty"`

	// All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
	DefaultLang *PbsDefaultLangEnum `json:"default-lang,omitempty"`

	// List of properties to delete.
	Delete []PbsNodesConfigInlineEnum `json:"delete,omitempty"`

	// Comment (multiple lines).
	Description *string `json:"description,omitempty"`

	// Digest to protect against concurrent updates
	Digest *string `json:"digest,omitempty"`

	// E-Mail Address.
	EmailFrom *string `json:"email-from,omitempty" validate:"regexp=^[[:^cntrl:]]*$"`

	// HTTP proxy configuration [http://]<host>[:port]
	HttpProxy *string `json:"http-proxy,omitempty"`

	// Maximum days to keep Task logs
	TaskLogMaxDays *int64 `json:"task-log-max-days,omitempty"`

}

// NewNodesConfigUpdateConfigRequest instantiates a new NodesConfigUpdateConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodesConfigUpdateConfigRequest() *NodesConfigUpdateConfigRequest {
	this := NodesConfigUpdateConfigRequest{}
	return &this
}

// NewNodesConfigUpdateConfigRequestWithDefaults instantiates a new NodesConfigUpdateConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodesConfigUpdateConfigRequestWithDefaults() *NodesConfigUpdateConfigRequest {
	this := NodesConfigUpdateConfigRequest{}

















	return &this
}


// GetAcme returns the Acme field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcme() PbsAcmeField {
	if o == nil || IsNil(o.Acme) {
		var ret PbsAcmeField
		return ret
	}
	return *o.Acme
}

// GetAcmeOk returns a tuple with the Acme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmeOk() (*PbsAcmeField, bool) {
	if o == nil || IsNil(o.Acme) {
		return nil, false
	}
	return o.Acme, true
}

// HasAcme returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcme() bool {
	if o != nil && !IsNil(o.Acme) {
		return true
	}

	return false
}

// SetAcme gets a reference to the given PbsAcmeField and assigns it to the Acme field.
func (o *NodesConfigUpdateConfigRequest) SetAcme(v PbsAcmeField) {
	o.Acme = &v
}


// GetAcmedomain0 returns the Acmedomain0 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain0() PbsAcmedomainField {
	if o == nil || IsNil(o.Acmedomain0) {
		var ret PbsAcmedomainField
		return ret
	}
	return *o.Acmedomain0
}

// GetAcmedomain0Ok returns a tuple with the Acmedomain0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain0Ok() (*PbsAcmedomainField, bool) {
	if o == nil || IsNil(o.Acmedomain0) {
		return nil, false
	}
	return o.Acmedomain0, true
}

// HasAcmedomain0 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcmedomain0() bool {
	if o != nil && !IsNil(o.Acmedomain0) {
		return true
	}

	return false
}

// SetAcmedomain0 gets a reference to the given PbsAcmedomainField and assigns it to the Acmedomain0 field.
func (o *NodesConfigUpdateConfigRequest) SetAcmedomain0(v PbsAcmedomainField) {
	o.Acmedomain0 = &v
}


// GetAcmedomain1 returns the Acmedomain1 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain1() PbsAcmedomainField {
	if o == nil || IsNil(o.Acmedomain1) {
		var ret PbsAcmedomainField
		return ret
	}
	return *o.Acmedomain1
}

// GetAcmedomain1Ok returns a tuple with the Acmedomain1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain1Ok() (*PbsAcmedomainField, bool) {
	if o == nil || IsNil(o.Acmedomain1) {
		return nil, false
	}
	return o.Acmedomain1, true
}

// HasAcmedomain1 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcmedomain1() bool {
	if o != nil && !IsNil(o.Acmedomain1) {
		return true
	}

	return false
}

// SetAcmedomain1 gets a reference to the given PbsAcmedomainField and assigns it to the Acmedomain1 field.
func (o *NodesConfigUpdateConfigRequest) SetAcmedomain1(v PbsAcmedomainField) {
	o.Acmedomain1 = &v
}


// GetAcmedomain2 returns the Acmedomain2 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain2() PbsAcmedomainField {
	if o == nil || IsNil(o.Acmedomain2) {
		var ret PbsAcmedomainField
		return ret
	}
	return *o.Acmedomain2
}

// GetAcmedomain2Ok returns a tuple with the Acmedomain2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain2Ok() (*PbsAcmedomainField, bool) {
	if o == nil || IsNil(o.Acmedomain2) {
		return nil, false
	}
	return o.Acmedomain2, true
}

// HasAcmedomain2 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcmedomain2() bool {
	if o != nil && !IsNil(o.Acmedomain2) {
		return true
	}

	return false
}

// SetAcmedomain2 gets a reference to the given PbsAcmedomainField and assigns it to the Acmedomain2 field.
func (o *NodesConfigUpdateConfigRequest) SetAcmedomain2(v PbsAcmedomainField) {
	o.Acmedomain2 = &v
}


// GetAcmedomain3 returns the Acmedomain3 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain3() PbsAcmedomainField {
	if o == nil || IsNil(o.Acmedomain3) {
		var ret PbsAcmedomainField
		return ret
	}
	return *o.Acmedomain3
}

// GetAcmedomain3Ok returns a tuple with the Acmedomain3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain3Ok() (*PbsAcmedomainField, bool) {
	if o == nil || IsNil(o.Acmedomain3) {
		return nil, false
	}
	return o.Acmedomain3, true
}

// HasAcmedomain3 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcmedomain3() bool {
	if o != nil && !IsNil(o.Acmedomain3) {
		return true
	}

	return false
}

// SetAcmedomain3 gets a reference to the given PbsAcmedomainField and assigns it to the Acmedomain3 field.
func (o *NodesConfigUpdateConfigRequest) SetAcmedomain3(v PbsAcmedomainField) {
	o.Acmedomain3 = &v
}


// GetAcmedomain4 returns the Acmedomain4 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain4() PbsAcmedomainField {
	if o == nil || IsNil(o.Acmedomain4) {
		var ret PbsAcmedomainField
		return ret
	}
	return *o.Acmedomain4
}

// GetAcmedomain4Ok returns a tuple with the Acmedomain4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetAcmedomain4Ok() (*PbsAcmedomainField, bool) {
	if o == nil || IsNil(o.Acmedomain4) {
		return nil, false
	}
	return o.Acmedomain4, true
}

// HasAcmedomain4 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasAcmedomain4() bool {
	if o != nil && !IsNil(o.Acmedomain4) {
		return true
	}

	return false
}

// SetAcmedomain4 gets a reference to the given PbsAcmedomainField and assigns it to the Acmedomain4 field.
func (o *NodesConfigUpdateConfigRequest) SetAcmedomain4(v PbsAcmedomainField) {
	o.Acmedomain4 = &v
}


// GetCiphersTls12 returns the CiphersTls12 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls12() string {
	if o == nil || IsNil(o.CiphersTls12) {
		var ret string
		return ret
	}
	return *o.CiphersTls12
}

// GetCiphersTls12Ok returns a tuple with the CiphersTls12 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls12Ok() (*string, bool) {
	if o == nil || IsNil(o.CiphersTls12) {
		return nil, false
	}
	return o.CiphersTls12, true
}

// HasCiphersTls12 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasCiphersTls12() bool {
	if o != nil && !IsNil(o.CiphersTls12) {
		return true
	}

	return false
}

// SetCiphersTls12 gets a reference to the given string and assigns it to the CiphersTls12 field.
func (o *NodesConfigUpdateConfigRequest) SetCiphersTls12(v string) {
	o.CiphersTls12 = &v
}


// GetCiphersTls13 returns the CiphersTls13 field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls13() string {
	if o == nil || IsNil(o.CiphersTls13) {
		var ret string
		return ret
	}
	return *o.CiphersTls13
}

// GetCiphersTls13Ok returns a tuple with the CiphersTls13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetCiphersTls13Ok() (*string, bool) {
	if o == nil || IsNil(o.CiphersTls13) {
		return nil, false
	}
	return o.CiphersTls13, true
}

// HasCiphersTls13 returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasCiphersTls13() bool {
	if o != nil && !IsNil(o.CiphersTls13) {
		return true
	}

	return false
}

// SetCiphersTls13 gets a reference to the given string and assigns it to the CiphersTls13 field.
func (o *NodesConfigUpdateConfigRequest) SetCiphersTls13(v string) {
	o.CiphersTls13 = &v
}


// GetConsentText returns the ConsentText field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetConsentText() string {
	if o == nil || IsNil(o.ConsentText) {
		var ret string
		return ret
	}
	return *o.ConsentText
}

// GetConsentTextOk returns a tuple with the ConsentText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetConsentTextOk() (*string, bool) {
	if o == nil || IsNil(o.ConsentText) {
		return nil, false
	}
	return o.ConsentText, true
}

// HasConsentText returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasConsentText() bool {
	if o != nil && !IsNil(o.ConsentText) {
		return true
	}

	return false
}

// SetConsentText gets a reference to the given string and assigns it to the ConsentText field.
func (o *NodesConfigUpdateConfigRequest) SetConsentText(v string) {
	o.ConsentText = &v
}


// GetDefaultLang returns the DefaultLang field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDefaultLang() PbsDefaultLangEnum {
	if o == nil || IsNil(o.DefaultLang) {
		var ret PbsDefaultLangEnum
		return ret
	}
	return *o.DefaultLang
}

// GetDefaultLangOk returns a tuple with the DefaultLang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDefaultLangOk() (*PbsDefaultLangEnum, bool) {
	if o == nil || IsNil(o.DefaultLang) {
		return nil, false
	}
	return o.DefaultLang, true
}

// HasDefaultLang returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDefaultLang() bool {
	if o != nil && !IsNil(o.DefaultLang) {
		return true
	}

	return false
}

// SetDefaultLang gets a reference to the given PbsDefaultLangEnum and assigns it to the DefaultLang field.
func (o *NodesConfigUpdateConfigRequest) SetDefaultLang(v PbsDefaultLangEnum) {
	o.DefaultLang = &v
}


// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDelete() []PbsNodesConfigInlineEnum {
	if o == nil || IsNil(o.Delete) {
		var ret []PbsNodesConfigInlineEnum
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDeleteOk() ([]PbsNodesConfigInlineEnum, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []PbsNodesConfigInlineEnum and assigns it to the Delete field.
func (o *NodesConfigUpdateConfigRequest) SetDelete(v []PbsNodesConfigInlineEnum) {
	o.Delete = v
}


// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NodesConfigUpdateConfigRequest) SetDescription(v string) {
	o.Description = &v
}


// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *NodesConfigUpdateConfigRequest) SetDigest(v string) {
	o.Digest = &v
}


// GetEmailFrom returns the EmailFrom field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetEmailFrom() string {
	if o == nil || IsNil(o.EmailFrom) {
		var ret string
		return ret
	}
	return *o.EmailFrom
}

// GetEmailFromOk returns a tuple with the EmailFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetEmailFromOk() (*string, bool) {
	if o == nil || IsNil(o.EmailFrom) {
		return nil, false
	}
	return o.EmailFrom, true
}

// HasEmailFrom returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasEmailFrom() bool {
	if o != nil && !IsNil(o.EmailFrom) {
		return true
	}

	return false
}

// SetEmailFrom gets a reference to the given string and assigns it to the EmailFrom field.
func (o *NodesConfigUpdateConfigRequest) SetEmailFrom(v string) {
	o.EmailFrom = &v
}


// GetHttpProxy returns the HttpProxy field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetHttpProxy() string {
	if o == nil || IsNil(o.HttpProxy) {
		var ret string
		return ret
	}
	return *o.HttpProxy
}

// GetHttpProxyOk returns a tuple with the HttpProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetHttpProxyOk() (*string, bool) {
	if o == nil || IsNil(o.HttpProxy) {
		return nil, false
	}
	return o.HttpProxy, true
}

// HasHttpProxy returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasHttpProxy() bool {
	if o != nil && !IsNil(o.HttpProxy) {
		return true
	}

	return false
}

// SetHttpProxy gets a reference to the given string and assigns it to the HttpProxy field.
func (o *NodesConfigUpdateConfigRequest) SetHttpProxy(v string) {
	o.HttpProxy = &v
}


// GetTaskLogMaxDays returns the TaskLogMaxDays field value if set, zero value otherwise.
func (o *NodesConfigUpdateConfigRequest) GetTaskLogMaxDays() int64 {
	if o == nil || IsNil(o.TaskLogMaxDays) {
		var ret int64
		return ret
	}
	return *o.TaskLogMaxDays
}

// GetTaskLogMaxDaysOk returns a tuple with the TaskLogMaxDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodesConfigUpdateConfigRequest) GetTaskLogMaxDaysOk() (*int64, bool) {
	if o == nil || IsNil(o.TaskLogMaxDays) {
		return nil, false
	}
	return o.TaskLogMaxDays, true
}

// HasTaskLogMaxDays returns a boolean if a field has been set.
func (o *NodesConfigUpdateConfigRequest) HasTaskLogMaxDays() bool {
	if o != nil && !IsNil(o.TaskLogMaxDays) {
		return true
	}

	return false
}

// SetTaskLogMaxDays gets a reference to the given int64 and assigns it to the TaskLogMaxDays field.
func (o *NodesConfigUpdateConfigRequest) SetTaskLogMaxDays(v int64) {
	o.TaskLogMaxDays = &v
}


func (o NodesConfigUpdateConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodesConfigUpdateConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if !IsNil(o.Acme) {
		toSerialize["acme"] = o.Acme
	}
	
	if !IsNil(o.Acmedomain0) {
		toSerialize["acmedomain0"] = o.Acmedomain0
	}
	
	if !IsNil(o.Acmedomain1) {
		toSerialize["acmedomain1"] = o.Acmedomain1
	}
	
	if !IsNil(o.Acmedomain2) {
		toSerialize["acmedomain2"] = o.Acmedomain2
	}
	
	if !IsNil(o.Acmedomain3) {
		toSerialize["acmedomain3"] = o.Acmedomain3
	}
	
	if !IsNil(o.Acmedomain4) {
		toSerialize["acmedomain4"] = o.Acmedomain4
	}
	
	if !IsNil(o.CiphersTls12) {
		toSerialize["ciphers-tls-1.2"] = o.CiphersTls12
	}
	
	if !IsNil(o.CiphersTls13) {
		toSerialize["ciphers-tls-1.3"] = o.CiphersTls13
	}
	
	if !IsNil(o.ConsentText) {
		toSerialize["consent-text"] = o.ConsentText
	}
	
	if !IsNil(o.DefaultLang) {
		toSerialize["default-lang"] = o.DefaultLang
	}
	
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	
	if !IsNil(o.EmailFrom) {
		toSerialize["email-from"] = o.EmailFrom
	}
	
	if !IsNil(o.HttpProxy) {
		toSerialize["http-proxy"] = o.HttpProxy
	}
	
	if !IsNil(o.TaskLogMaxDays) {
		toSerialize["task-log-max-days"] = o.TaskLogMaxDays
	}
	
	return toSerialize, nil
}

type NullableNodesConfigUpdateConfigRequest struct {
	value *NodesConfigUpdateConfigRequest
	isSet bool
}

func (v NullableNodesConfigUpdateConfigRequest) Get() *NodesConfigUpdateConfigRequest {
	return v.value
}

func (v *NullableNodesConfigUpdateConfigRequest) Set(val *NodesConfigUpdateConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodesConfigUpdateConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodesConfigUpdateConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodesConfigUpdateConfigRequest(val *NodesConfigUpdateConfigRequest) *NullableNodesConfigUpdateConfigRequest {
	return &NullableNodesConfigUpdateConfigRequest{value: val, isSet: true}
}

func (v NullableNodesConfigUpdateConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodesConfigUpdateConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


