/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsNodesSubscriptionStatusEnum the model 'PbsNodesSubscriptionStatusEnum'
type PbsNodesSubscriptionStatusEnum string

// List of PbsNodesSubscriptionStatusEnum
const (
	PBSNODESSUBSCRIPTIONSTATUSENUM_NEW PbsNodesSubscriptionStatusEnum = "new"
	PBSNODESSUBSCRIPTIONSTATUSENUM_NOTFOUND PbsNodesSubscriptionStatusEnum = "notfound"
	PBSNODESSUBSCRIPTIONSTATUSENUM_ACTIVE PbsNodesSubscriptionStatusEnum = "active"
	PBSNODESSUBSCRIPTIONSTATUSENUM_INVALID PbsNodesSubscriptionStatusEnum = "invalid"
	PBSNODESSUBSCRIPTIONSTATUSENUM_EXPIRED PbsNodesSubscriptionStatusEnum = "expired"
	PBSNODESSUBSCRIPTIONSTATUSENUM_SUSPENDED PbsNodesSubscriptionStatusEnum = "suspended"
)

// All allowed values of PbsNodesSubscriptionStatusEnum enum
var AllowedPbsNodesSubscriptionStatusEnumEnumValues = []PbsNodesSubscriptionStatusEnum{
	"new",
	"notfound",
	"active",
	"invalid",
	"expired",
	"suspended",
}

func (v *PbsNodesSubscriptionStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsNodesSubscriptionStatusEnum(value)
	for _, existing := range AllowedPbsNodesSubscriptionStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsNodesSubscriptionStatusEnum", value)
}

// NewPbsNodesSubscriptionStatusEnumFromValue returns a pointer to a valid PbsNodesSubscriptionStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsNodesSubscriptionStatusEnumFromValue(v string) (*PbsNodesSubscriptionStatusEnum, error) {
	ev := PbsNodesSubscriptionStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsNodesSubscriptionStatusEnum: valid values are %v", v, AllowedPbsNodesSubscriptionStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsNodesSubscriptionStatusEnum) IsValid() bool {
	for _, existing := range AllowedPbsNodesSubscriptionStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsNodesSubscriptionStatusEnum value
func (v PbsNodesSubscriptionStatusEnum) Ptr() *PbsNodesSubscriptionStatusEnum {
	return &v
}

type NullablePbsNodesSubscriptionStatusEnum struct {
	value *PbsNodesSubscriptionStatusEnum
	isSet bool
}

func (v NullablePbsNodesSubscriptionStatusEnum) Get() *PbsNodesSubscriptionStatusEnum {
	return v.value
}

func (v *NullablePbsNodesSubscriptionStatusEnum) Set(val *PbsNodesSubscriptionStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsNodesSubscriptionStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsNodesSubscriptionStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsNodesSubscriptionStatusEnum(val *PbsNodesSubscriptionStatusEnum) *NullablePbsNodesSubscriptionStatusEnum {
	return &NullablePbsNodesSubscriptionStatusEnum{value: val, isSet: true}
}

func (v NullablePbsNodesSubscriptionStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsNodesSubscriptionStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

