/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsUsageTypeEnum the model 'PbsUsageTypeEnum'
type PbsUsageTypeEnum string

// List of PbsUsageTypeEnum
const (
	PBSUSAGETYPEENUM_UNUSED PbsUsageTypeEnum = "unused"
	PBSUSAGETYPEENUM_MOUNTED PbsUsageTypeEnum = "mounted"
	PBSUSAGETYPEENUM_LVM PbsUsageTypeEnum = "lvm"
	PBSUSAGETYPEENUM_ZFS PbsUsageTypeEnum = "zfs"
	PBSUSAGETYPEENUM_DEVICEMAPPER PbsUsageTypeEnum = "devicemapper"
	PBSUSAGETYPEENUM_PARTITIONS PbsUsageTypeEnum = "partitions"
	PBSUSAGETYPEENUM_FILESYSTEM PbsUsageTypeEnum = "filesystem"
)

// All allowed values of PbsUsageTypeEnum enum
var AllowedPbsUsageTypeEnumEnumValues = []PbsUsageTypeEnum{
	"unused",
	"mounted",
	"lvm",
	"zfs",
	"devicemapper",
	"partitions",
	"filesystem",
}

func (v *PbsUsageTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsUsageTypeEnum(value)
	for _, existing := range AllowedPbsUsageTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsUsageTypeEnum", value)
}

// NewPbsUsageTypeEnumFromValue returns a pointer to a valid PbsUsageTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsUsageTypeEnumFromValue(v string) (*PbsUsageTypeEnum, error) {
	ev := PbsUsageTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsUsageTypeEnum: valid values are %v", v, AllowedPbsUsageTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsUsageTypeEnum) IsValid() bool {
	for _, existing := range AllowedPbsUsageTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsUsageTypeEnum value
func (v PbsUsageTypeEnum) Ptr() *PbsUsageTypeEnum {
	return &v
}

type NullablePbsUsageTypeEnum struct {
	value *PbsUsageTypeEnum
	isSet bool
}

func (v NullablePbsUsageTypeEnum) Get() *PbsUsageTypeEnum {
	return v.value
}

func (v *NullablePbsUsageTypeEnum) Set(val *PbsUsageTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsUsageTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsUsageTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsUsageTypeEnum(val *PbsUsageTypeEnum) *NullablePbsUsageTypeEnum {
	return &NullablePbsUsageTypeEnum{value: val, isSet: true}
}

func (v NullablePbsUsageTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsUsageTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

