/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsConfigDatastoreInlineEnum the model 'PbsConfigDatastoreInlineEnum'
type PbsConfigDatastoreInlineEnum string

// List of PbsConfigDatastoreInlineEnum
const (
	PBSCONFIGDATASTOREINLINEENUM_COMMENT PbsConfigDatastoreInlineEnum = "comment"
	PBSCONFIGDATASTOREINLINEENUM_GC_SCHEDULE PbsConfigDatastoreInlineEnum = "gc-schedule"
	PBSCONFIGDATASTOREINLINEENUM_GC_ON_UNMOUNT PbsConfigDatastoreInlineEnum = "gc-on-unmount"
	PBSCONFIGDATASTOREINLINEENUM_PRUNE_SCHEDULE PbsConfigDatastoreInlineEnum = "prune-schedule"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_LAST PbsConfigDatastoreInlineEnum = "keep-last"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_HOURLY PbsConfigDatastoreInlineEnum = "keep-hourly"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_DAILY PbsConfigDatastoreInlineEnum = "keep-daily"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_WEEKLY PbsConfigDatastoreInlineEnum = "keep-weekly"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_MONTHLY PbsConfigDatastoreInlineEnum = "keep-monthly"
	PBSCONFIGDATASTOREINLINEENUM_KEEP_YEARLY PbsConfigDatastoreInlineEnum = "keep-yearly"
	PBSCONFIGDATASTOREINLINEENUM_VERIFY_NEW PbsConfigDatastoreInlineEnum = "verify-new"
	PBSCONFIGDATASTOREINLINEENUM_NOTIFY_USER PbsConfigDatastoreInlineEnum = "notify-user"
	PBSCONFIGDATASTOREINLINEENUM_NOTIFY PbsConfigDatastoreInlineEnum = "notify"
	PBSCONFIGDATASTOREINLINEENUM_NOTIFICATION_MODE PbsConfigDatastoreInlineEnum = "notification-mode"
	PBSCONFIGDATASTOREINLINEENUM_TUNING PbsConfigDatastoreInlineEnum = "tuning"
	PBSCONFIGDATASTOREINLINEENUM_MAINTENANCE_MODE PbsConfigDatastoreInlineEnum = "maintenance-mode"
	PBSCONFIGDATASTOREINLINEENUM_NOTIFICATION_THRESHOLDS PbsConfigDatastoreInlineEnum = "notification-thresholds"
	PBSCONFIGDATASTOREINLINEENUM_COUNTER_RESET_SCHEDULE PbsConfigDatastoreInlineEnum = "counter-reset-schedule"
)

// All allowed values of PbsConfigDatastoreInlineEnum enum
var AllowedPbsConfigDatastoreInlineEnumEnumValues = []PbsConfigDatastoreInlineEnum{
	"comment",
	"gc-schedule",
	"gc-on-unmount",
	"prune-schedule",
	"keep-last",
	"keep-hourly",
	"keep-daily",
	"keep-weekly",
	"keep-monthly",
	"keep-yearly",
	"verify-new",
	"notify-user",
	"notify",
	"notification-mode",
	"tuning",
	"maintenance-mode",
	"notification-thresholds",
	"counter-reset-schedule",
}

func (v *PbsConfigDatastoreInlineEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsConfigDatastoreInlineEnum(value)
	for _, existing := range AllowedPbsConfigDatastoreInlineEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsConfigDatastoreInlineEnum", value)
}

// NewPbsConfigDatastoreInlineEnumFromValue returns a pointer to a valid PbsConfigDatastoreInlineEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsConfigDatastoreInlineEnumFromValue(v string) (*PbsConfigDatastoreInlineEnum, error) {
	ev := PbsConfigDatastoreInlineEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsConfigDatastoreInlineEnum: valid values are %v", v, AllowedPbsConfigDatastoreInlineEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsConfigDatastoreInlineEnum) IsValid() bool {
	for _, existing := range AllowedPbsConfigDatastoreInlineEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsConfigDatastoreInlineEnum value
func (v PbsConfigDatastoreInlineEnum) Ptr() *PbsConfigDatastoreInlineEnum {
	return &v
}

type NullablePbsConfigDatastoreInlineEnum struct {
	value *PbsConfigDatastoreInlineEnum
	isSet bool
}

func (v NullablePbsConfigDatastoreInlineEnum) Get() *PbsConfigDatastoreInlineEnum {
	return v.value
}

func (v *NullablePbsConfigDatastoreInlineEnum) Set(val *PbsConfigDatastoreInlineEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsConfigDatastoreInlineEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsConfigDatastoreInlineEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsConfigDatastoreInlineEnum(val *PbsConfigDatastoreInlineEnum) *NullablePbsConfigDatastoreInlineEnum {
	return &NullablePbsConfigDatastoreInlineEnum{value: val, isSet: true}
}

func (v NullablePbsConfigDatastoreInlineEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsConfigDatastoreInlineEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

