/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminDatastoreUpdateGroupNotesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminDatastoreUpdateGroupNotesRequest{}

// AdminDatastoreUpdateGroupNotesRequest struct for AdminDatastoreUpdateGroupNotesRequest
type AdminDatastoreUpdateGroupNotesRequest struct {

	// Backup ID.
	BackupId string `json:"backup-id" validate:"regexp=^[A-Za-z0-9_][A-Za-z0-9._\\\\-]*$"`

	// Backup types.
	BackupType PbsBackupTypeEnum `json:"backup-type"`

	// A multiline text.
	Notes string `json:"notes"`

	// Namespace.
	Ns *string `json:"ns,omitempty" validate:"regexp=^(?:(?:(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*)/){0,7}(?:[A-Za-z0-9_][A-Za-z0-9._\\\\-]*))?$"`

}

type _AdminDatastoreUpdateGroupNotesRequest AdminDatastoreUpdateGroupNotesRequest

// NewAdminDatastoreUpdateGroupNotesRequest instantiates a new AdminDatastoreUpdateGroupNotesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminDatastoreUpdateGroupNotesRequest(backupId string, backupType PbsBackupTypeEnum, notes string) *AdminDatastoreUpdateGroupNotesRequest {
	this := AdminDatastoreUpdateGroupNotesRequest{}
	this.BackupId = backupId
	this.BackupType = backupType
	this.Notes = notes
	return &this
}

// NewAdminDatastoreUpdateGroupNotesRequestWithDefaults instantiates a new AdminDatastoreUpdateGroupNotesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminDatastoreUpdateGroupNotesRequestWithDefaults() *AdminDatastoreUpdateGroupNotesRequest {
	this := AdminDatastoreUpdateGroupNotesRequest{}





	return &this
}


// GetBackupId returns the BackupId field value
func (o *AdminDatastoreUpdateGroupNotesRequest) GetBackupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value
// and a boolean to check if the value has been set.
func (o *AdminDatastoreUpdateGroupNotesRequest) GetBackupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupId, true
}

// SetBackupId sets field value
func (o *AdminDatastoreUpdateGroupNotesRequest) SetBackupId(v string) {
	o.BackupId = v
}


// GetBackupType returns the BackupType field value
func (o *AdminDatastoreUpdateGroupNotesRequest) GetBackupType() PbsBackupTypeEnum {
	if o == nil {
		var ret PbsBackupTypeEnum
		return ret
	}

	return o.BackupType
}

// GetBackupTypeOk returns a tuple with the BackupType field value
// and a boolean to check if the value has been set.
func (o *AdminDatastoreUpdateGroupNotesRequest) GetBackupTypeOk() (*PbsBackupTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupType, true
}

// SetBackupType sets field value
func (o *AdminDatastoreUpdateGroupNotesRequest) SetBackupType(v PbsBackupTypeEnum) {
	o.BackupType = v
}


// GetNotes returns the Notes field value
func (o *AdminDatastoreUpdateGroupNotesRequest) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *AdminDatastoreUpdateGroupNotesRequest) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *AdminDatastoreUpdateGroupNotesRequest) SetNotes(v string) {
	o.Notes = v
}


// GetNs returns the Ns field value if set, zero value otherwise.
func (o *AdminDatastoreUpdateGroupNotesRequest) GetNs() string {
	if o == nil || IsNil(o.Ns) {
		var ret string
		return ret
	}
	return *o.Ns
}

// GetNsOk returns a tuple with the Ns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminDatastoreUpdateGroupNotesRequest) GetNsOk() (*string, bool) {
	if o == nil || IsNil(o.Ns) {
		return nil, false
	}
	return o.Ns, true
}

// HasNs returns a boolean if a field has been set.
func (o *AdminDatastoreUpdateGroupNotesRequest) HasNs() bool {
	if o != nil && !IsNil(o.Ns) {
		return true
	}

	return false
}

// SetNs gets a reference to the given string and assigns it to the Ns field.
func (o *AdminDatastoreUpdateGroupNotesRequest) SetNs(v string) {
	o.Ns = &v
}


func (o AdminDatastoreUpdateGroupNotesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminDatastoreUpdateGroupNotesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	toSerialize["backup-id"] = o.BackupId
	
	toSerialize["backup-type"] = o.BackupType
	
	toSerialize["notes"] = o.Notes
	
	if !IsNil(o.Ns) {
		toSerialize["ns"] = o.Ns
	}
	
	return toSerialize, nil
}

func (o *AdminDatastoreUpdateGroupNotesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backup-id",
		"backup-type",
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminDatastoreUpdateGroupNotesRequest := _AdminDatastoreUpdateGroupNotesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminDatastoreUpdateGroupNotesRequest)

	if err != nil {
		return err
	}

	*o = AdminDatastoreUpdateGroupNotesRequest(varAdminDatastoreUpdateGroupNotesRequest)

	return err
}

type NullableAdminDatastoreUpdateGroupNotesRequest struct {
	value *AdminDatastoreUpdateGroupNotesRequest
	isSet bool
}

func (v NullableAdminDatastoreUpdateGroupNotesRequest) Get() *AdminDatastoreUpdateGroupNotesRequest {
	return v.value
}

func (v *NullableAdminDatastoreUpdateGroupNotesRequest) Set(val *AdminDatastoreUpdateGroupNotesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminDatastoreUpdateGroupNotesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminDatastoreUpdateGroupNotesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminDatastoreUpdateGroupNotesRequest(val *AdminDatastoreUpdateGroupNotesRequest) *NullableAdminDatastoreUpdateGroupNotesRequest {
	return &NullableAdminDatastoreUpdateGroupNotesRequest{value: val, isSet: true}
}

func (v NullableAdminDatastoreUpdateGroupNotesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminDatastoreUpdateGroupNotesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


