/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsMountStatusEnum the model 'PbsMountStatusEnum'
type PbsMountStatusEnum string

// List of PbsMountStatusEnum
const (
	PBSMOUNTSTATUSENUM_MOUNTED PbsMountStatusEnum = "mounted"
	PBSMOUNTSTATUSENUM_NOTMOUNTED PbsMountStatusEnum = "notmounted"
	PBSMOUNTSTATUSENUM_NONREMOVABLE PbsMountStatusEnum = "nonremovable"
)

// All allowed values of PbsMountStatusEnum enum
var AllowedPbsMountStatusEnumEnumValues = []PbsMountStatusEnum{
	"mounted",
	"notmounted",
	"nonremovable",
}

func (v *PbsMountStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsMountStatusEnum(value)
	for _, existing := range AllowedPbsMountStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsMountStatusEnum", value)
}

// NewPbsMountStatusEnumFromValue returns a pointer to a valid PbsMountStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsMountStatusEnumFromValue(v string) (*PbsMountStatusEnum, error) {
	ev := PbsMountStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsMountStatusEnum: valid values are %v", v, AllowedPbsMountStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsMountStatusEnum) IsValid() bool {
	for _, existing := range AllowedPbsMountStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsMountStatusEnum value
func (v PbsMountStatusEnum) Ptr() *PbsMountStatusEnum {
	return &v
}

type NullablePbsMountStatusEnum struct {
	value *PbsMountStatusEnum
	isSet bool
}

func (v NullablePbsMountStatusEnum) Get() *PbsMountStatusEnum {
	return v.value
}

func (v *NullablePbsMountStatusEnum) Set(val *PbsMountStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsMountStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsMountStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsMountStatusEnum(val *PbsMountStatusEnum) *NullablePbsMountStatusEnum {
	return &NullablePbsMountStatusEnum{value: val, isSet: true}
}

func (v NullablePbsMountStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsMountStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

