/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PbsAcrValuesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PbsAcrValuesConfig{}

// PbsAcrValuesConfig struct for PbsAcrValuesConfig
type PbsAcrValuesConfig struct {

	Description interface{} `json:"description"`

	// OpenID Authentication Context Class Reference.
	Items string `json:"items" validate:"regexp=^[^\\\\x00-\\\\x1F\\\\x7F <>#\\\\u0022]*$"`

	Type interface{} `json:"type"`

}

type _PbsAcrValuesConfig PbsAcrValuesConfig

// NewPbsAcrValuesConfig instantiates a new PbsAcrValuesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPbsAcrValuesConfig(description interface{}, items string, type_ interface{}) *PbsAcrValuesConfig {
	this := PbsAcrValuesConfig{}
	this.Description = description
	this.Items = items
	this.Type = type_
	return &this
}

// NewPbsAcrValuesConfigWithDefaults instantiates a new PbsAcrValuesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPbsAcrValuesConfigWithDefaults() *PbsAcrValuesConfig {
	this := PbsAcrValuesConfig{}




	return &this
}


// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PbsAcrValuesConfig) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PbsAcrValuesConfig) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PbsAcrValuesConfig) SetDescription(v interface{}) {
	o.Description = v
}


// GetItems returns the Items field value
func (o *PbsAcrValuesConfig) GetItems() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PbsAcrValuesConfig) GetItemsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *PbsAcrValuesConfig) SetItems(v string) {
	o.Items = v
}


// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PbsAcrValuesConfig) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PbsAcrValuesConfig) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PbsAcrValuesConfig) SetType(v interface{}) {
	o.Type = v
}


func (o PbsAcrValuesConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PbsAcrValuesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	
	toSerialize["items"] = o.Items
	
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	
	return toSerialize, nil
}

func (o *PbsAcrValuesConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"items",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPbsAcrValuesConfig := _PbsAcrValuesConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPbsAcrValuesConfig)

	if err != nil {
		return err
	}

	*o = PbsAcrValuesConfig(varPbsAcrValuesConfig)

	return err
}

type NullablePbsAcrValuesConfig struct {
	value *PbsAcrValuesConfig
	isSet bool
}

func (v NullablePbsAcrValuesConfig) Get() *PbsAcrValuesConfig {
	return v.value
}

func (v *NullablePbsAcrValuesConfig) Set(val *PbsAcrValuesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsAcrValuesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsAcrValuesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsAcrValuesConfig(val *PbsAcrValuesConfig) *NullablePbsAcrValuesConfig {
	return &NullablePbsAcrValuesConfig{value: val, isSet: true}
}

func (v NullablePbsAcrValuesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsAcrValuesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


