/*
Proxmox Backup Server API

Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.

API version: 9.x
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PbsConfigNotificationsInlineEnum4 the model 'PbsConfigNotificationsInlineEnum4'
type PbsConfigNotificationsInlineEnum4 string

// List of PbsConfigNotificationsInlineEnum4
const (
	PBSCONFIGNOTIFICATIONSINLINEENUM4_COMMENT PbsConfigNotificationsInlineEnum4 = "comment"
	PBSCONFIGNOTIFICATIONSINLINEENUM4_DISABLE PbsConfigNotificationsInlineEnum4 = "disable"
	PBSCONFIGNOTIFICATIONSINLINEENUM4_HEADER PbsConfigNotificationsInlineEnum4 = "header"
	PBSCONFIGNOTIFICATIONSINLINEENUM4_BODY PbsConfigNotificationsInlineEnum4 = "body"
	PBSCONFIGNOTIFICATIONSINLINEENUM4_SECRET PbsConfigNotificationsInlineEnum4 = "secret"
)

// All allowed values of PbsConfigNotificationsInlineEnum4 enum
var AllowedPbsConfigNotificationsInlineEnum4EnumValues = []PbsConfigNotificationsInlineEnum4{
	"comment",
	"disable",
	"header",
	"body",
	"secret",
}

func (v *PbsConfigNotificationsInlineEnum4) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PbsConfigNotificationsInlineEnum4(value)
	for _, existing := range AllowedPbsConfigNotificationsInlineEnum4EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PbsConfigNotificationsInlineEnum4", value)
}

// NewPbsConfigNotificationsInlineEnum4FromValue returns a pointer to a valid PbsConfigNotificationsInlineEnum4
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPbsConfigNotificationsInlineEnum4FromValue(v string) (*PbsConfigNotificationsInlineEnum4, error) {
	ev := PbsConfigNotificationsInlineEnum4(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PbsConfigNotificationsInlineEnum4: valid values are %v", v, AllowedPbsConfigNotificationsInlineEnum4EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PbsConfigNotificationsInlineEnum4) IsValid() bool {
	for _, existing := range AllowedPbsConfigNotificationsInlineEnum4EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PbsConfigNotificationsInlineEnum4 value
func (v PbsConfigNotificationsInlineEnum4) Ptr() *PbsConfigNotificationsInlineEnum4 {
	return &v
}

type NullablePbsConfigNotificationsInlineEnum4 struct {
	value *PbsConfigNotificationsInlineEnum4
	isSet bool
}

func (v NullablePbsConfigNotificationsInlineEnum4) Get() *PbsConfigNotificationsInlineEnum4 {
	return v.value
}

func (v *NullablePbsConfigNotificationsInlineEnum4) Set(val *PbsConfigNotificationsInlineEnum4) {
	v.value = val
	v.isSet = true
}

func (v NullablePbsConfigNotificationsInlineEnum4) IsSet() bool {
	return v.isSet
}

func (v *NullablePbsConfigNotificationsInlineEnum4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePbsConfigNotificationsInlineEnum4(val *PbsConfigNotificationsInlineEnum4) *NullablePbsConfigNotificationsInlineEnum4 {
	return &NullablePbsConfigNotificationsInlineEnum4{value: val, isSet: true}
}

func (v NullablePbsConfigNotificationsInlineEnum4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePbsConfigNotificationsInlineEnum4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

