// Auto-generated by scripts/sdk-facades.ts. Do not edit.
// Brand-named alias for the top-level APIClient.

package openapi

type Pbs = APIClient

func NewPbs(cfg *Configuration) *Pbs {
	return NewAPIClient(cfg)
}
